apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-waltti
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-waltti-service-port
  selector:
    app: digitransit-ui-waltti
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-waltti
  labels:
    app: digitransit-ui-waltti
    update: auto
    restartAt: "03.10_13.10"
    restartLimitInterval: "480"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-waltti
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: digitransit-ui-waltti
    spec:
      priorityClassName: medium-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: digitransit-ui-waltti
        image: hsldevcom/digitransit-ui:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: API_URL
          value: "https://dev-api.digitransit.fi"
        - name: ASSET_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net/ui/v1/waltti"
        - name: OTP_URL
          value: "https://dev-api.digitransit.fi/routing/v1/routers/waltti/"
        - name: MAP_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net"
        - name: REALTIME_PATCH
          value: "{\"tampere\": {\"mqtt\": \"wss://dev-mqtt.lmj.fi:8443/mqtt\"}, \"Joensuu\": {\"mqtt\": \"wss://dev-mqtt.lmj.fi:8443/mqtt\"}, \"Lappeenranta\": {\"mqtt\": \"wss://dev-mqtt.lmj.fi:8443/mqtt\"}, \"Kuopio\": {\"mqtt\": \"wss://dev-mqtt.lmj.fi:8443/mqtt\"}, \"LINKKI\": {\"mqtt\": \"wss://dev-mqtt.lmj.fi:8443/mqtt\"}}"
        - name: NODE_OPTS
          value: "--max_old_space_size=900"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-dsn
              key: sentry-dsn
        - name: SENTRY_SECRET_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-secret-dsn
              key: sentry-secret-dsn
        - name: APIM_SUBSCRIPTION_KEY
          valueFrom:
            secretKeyRef:
              name: apim-subs-test-key
              key: apim-subs-test-key
        resources:
          requests:
            memory: 1200Mi
          limits:
            memory: 1200Mi
            cpu: 1000m
