apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-default
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-default-service-port
  selector:
    app: digitransit-ui-default
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-default
  labels:
    app: digitransit-ui-default
    update: auto
spec:
  selector:
    matchLabels:
      app: digitransit-ui-default
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: digitransit-ui-default
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: digitransit-ui-default
        image: hsldevcom/digitransit-ui:next # TODO!! CHANGE
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 10
          failureThreshold: 3
        env:
        - name: CONFIG
          value: "matka"
        - name: API_URL
          value: "https://dev-next-api.digitransit.fi"
        - name: ASSET_URL
          value: "https://digitransit-dev3-cdn-origin.azureedge.net/ui/v1/finland"
        - name: MAP_URL
          value: "https://digitransit-dev3-cdn-origin.azureedge.net"
        - name: NODE_OPTS
          value: "--max_old_space_size=600"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-dsn
              key: sentry-dsn
        - name: SENTRY_SECRET_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-secret-dsn
              key: sentry-secret-dsn
        resources:
          requests:
            memory: 800Mi
          limits:
            memory: 800Mi
            cpu: 200m
