apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-matka
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-matka-service-port
  selector:
    app: digitransit-ui-matka
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-matka
  labels:
    app: digitransit-ui-matka
    update: auto
    restartAt: "03.00_13.00"
    restartLimitInterval: "480"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-matka
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: digitransit-ui-matka
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: digitransit-ui-matka
        image: hsldevcom/digitransit-ui:next
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: CONFIG
          value: "matka"
        - name: API_URL
          value: "https://dev-next-api.digitransit.fi"
        - name: ASSET_URL
          value: "https://digitransit-dev3-cdn-origin.azureedge.net/ui/v1/finland"
        - name: MAP_URL
          value: "https://digitransit-dev3-cdn-origin.azureedge.net"
        - name: OTP_URL
          value: "https://dev-next-api.digitransit.fi/routing/v1/routers/next-finland/"
        - name: NODE_OPTS
          value: "--max_old_space_size=600"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-dsn
              key: sentry-dsn
        - name: SENTRY_SECRET_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-secret-dsn
              key: sentry-secret-dsn
        - name: APIM_SUBSCRIPTION_KEY
          valueFrom:
            secretKeyRef:
              name: apim-subs-test-key
              key: apim-subs-test-key
        resources:
          requests:
            memory: 1024Mi
          limits:
            memory: 1024Mi
            cpu: 1000m
