apiVersion: v1
kind: Service
metadata:
  name: hsl-timetable-builder
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: hsl-timetable-builder-service-port
  selector:
    app: hsl-timetable-builder
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsl-timetable-builder
  labels:
    app: hsl-timetable-builder
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hsl-timetable-builder
  template:
    metadata:
      labels:
        app: hsl-timetable-builder

    spec:
      containers:
      - name: hsl-timetable-builder
        image: hsldevcom/hsl-timetable-builder
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: "docker-sock-volume"
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        # TODO: network: BRIDGE ??
        ports:
        - containerPort: 8080
        env:
        - name: DOCKER_AUTH
          valueFrom:
            secretKeyRef:
              name: docker-auth
              key: docker-auth
        - name: DOCKER_TAG
          value: "kube-test"
        - name: DOCKER_USER
          valueFrom:
            secretKeyRef:
              name: docker-user
              key: docker-user
        - name: FONTSTACK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fontstack-password
              key: fontstack-password
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: slack-webhook
              key: slack-webhook
        - name: TAKU_API_URL
          valueFrom:
            secretKeyRef:
              name: taku-api
              key: taku-api
        - name: TAKU_KEY
          valueFrom:
            secretKeyRef:
              name: taku-key
              key: taku-key
        - name: TIMETABLE_DAYS_ADVANCE
          value: "2"
        resources:
          requests:
            memory: 1736Mi
          limits:
            memory: 1736Mi
            cpu: 1000m
      volumes:
        - name: "docker-sock-volume"
          hostPath:
             # location on host
            path: /var/run/docker.sock
