apiVersion: v1
kind: Service
metadata:
  name: hsl-map-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: hsl-map-server-service-port
    protocol: TCP
  selector:
    app: hsl-map-server
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsl-map-server
  labels:
    app: hsl-map-server
    update: auto
    # restartAfterDeployments: "opentripplanner-finland_opentripplanner-hsl_opentripplanner-waltti" 
    # restartDelay: "5" 
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: hsl-map-server
  template:
    metadata:
      labels:
        app: hsl-map-server  
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: hsl-map-server
        image: hsldevcom/hsl-map-server:kubernetes-dev #TODO: No tag? 
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        # TODO: network: BRIDGE ??
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 30
          httpGet:
            port: 8080
            path: /map/v1/hsl-map/index.json
        livenessProbe:
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
          httpGet:
            port: 8080
            path: /map/v1/hsl-map/index.json
        env:
          - name: FINLAND_OTP_URL
            value: "opentripplanner-finland:8080/otp/routers/finland/index/graphql" # Todo, may need to change this.
          - name: FONTSTACK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fontstack-password
                key: fontstack-password
          - name: HSL_OTP_URL
            value: "opentripplanner-hsl-next:8080/otp/routers/hsl/index/graphql" # Todo, may need to change this
          - name: NODE_OPTS
            value: "--max_old_space_size=2048 --optimize_for_size --max_executable_size=2048 --stack_size=2048 --harmony"
          - name: WALTTI_OTP_URL
            value: "opentripplanner-waltti:8080/otp/routers/waltti/index/graphql" # Todo, may need to change this
        resources:
          requests:
            memory: 4096Mi
          limits:
            memory: 4096Mi
            cpu: 500m         
