apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-hsl
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-hsl-service-port
  selector:
    app: opentripplanner-hsl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-hsl
  labels:
    app: opentripplanner-hsl
    update: auto
    restartAfterDeployments: "opentripplanner-data-con-hsl"
    restartDelay: "1"
    restartAt: "05.15"
    restartLimitInterval: "720"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: opentripplanner-hsl
  template:
    metadata:
      labels:
        app: opentripplanner-hsl
    spec:
      priorityClassName: medium-priority
      containers:
      - name: opentripplanner-hsl
        image: hsldevcom/opentripplanner:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/routers/hsl/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ROUTER_DATA_CONTAINER_URL
          value: "http://opentripplanner-data-con-hsl:8080"
        - name: ROUTER_NAME
          value: "hsl"
        - name: JAVA_OPTS
          valueFrom:
            secretKeyRef:
              name: otp-hsl-java-opts
              key: otp-hsl-java-opts
        resources:
          requests:
            memory: "9216Mi"
          limits:
            memory: "9216Mi"
            cpu: "1900m"
