---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otp-databuilder-dev-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: otp-data-builder-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: otp-data-builder-dev-service-port
  selector:
    app: otp-data-builder-dev
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-data-builder-dev
  labels:
    app: otp-data-builder-dev
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: otp-data-builder-dev
  template:
    metadata:
      labels:
        app: otp-data-builder-dev
    spec:
      containers:
      - name: otp-data-builder-dev
        image: hsldevcom/otp-data-builder:latest
        volumeMounts:
          - mountPath: var/run/docker.sock
            name: "docker-sock-volume"    
          - mountPath: opt/otp-data-builder/data    
            name: otp-data
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: BUILDER_TYPE
          value: "dev"
        - name: BUILD_TIME
          value: "23:00:00"
        - name: DOCKER_API_VERSION
          value: "1.38"
        - name: DATA
          value: "/opt/otp-data-builder/data"
        - name: DOCKER_AUTH
          valueFrom:
            secretKeyRef:
              name: docker-auth
              key: docker-auth
        - name: DOCKER_TAG
          value: "latest"
        - name: DOCKER_USER
          valueFrom:
            secretKeyRef:
              name: docker-user
              key: docker-user
        - name: EXTRA_SRC
          value: "{\"MatkahuoltoKainuu\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/kainuu-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"MatkahuoltoSavo\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/savo-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"MatkahuoltoKanta\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/kanta-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"MatkahuoltoKarjala\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/karjala-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"MatkahuoltoKeski\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/keski-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"MatkahuoltoKyme\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/kyme-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"MatkahuoltoLappi\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/lappi-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"MatkahuoltoPohjanmaa\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/pohjanmaa-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"MatkahuoltoSatakunta\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/satakunta-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"MatkahuoltoVakka\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/vakka-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"MatkahuoltoVantaa\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/vantaa-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"MatkahuoltoVarsinais\": {\"url\": \"http://digitransit-proxy:8080/out/minfoapi.matkahuolto.fi/gtfs/varsinais-fi/gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}, \"tampere\": {\"url\": \"http://www.tampere.fi/ekstrat/ptdata/tamperefeed_faret.zip\", \"routers\": [\"finland\", \"waltti\"]}, \"Salo\": {\"url\": \"https://tvv.fra1.digitaloceanspaces.com/239.zip\", \"fit\": true, \"routers\": [\"waltti\"]}}"
        - name: EXTRA_UPDATERS 
          value: "{\"foli-alerts\": {\"url\": \"https://foli-beta.nanona.fi/gtfs-rt/reittiopas\", \"routers\": [\"waltti\"]}, \"hsl-trip-updates\": {\"topic\": \"gtfsrt/dev/fi/hsl/tu\", \"routers\": [\"hsl\", \"finland\"]}, \"hsl-alerts\": {\"url\": \"https://dev-api.digitransit.fi/realtime/service-alerts/v2/hsl\", \"routers\": [\"hsl\", \"finland\"]}, \"hsl-rail-trip-updates\": {\"remove\": true, \"routers\": [\"hsl\", \"finland\"]}}"
        - name: HOST_DATA
          value: "/opt/otp-data"
        - name: OTP_TAG
          value: "latest"
        - name: ROUTERS
          value: "finland, waltti, hsl"
        - name: SEED_TAG
          value: "latest"
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: slack-webhook
              key: slack-webhook
        - name: TOOLS_TAG
          value: "latest"
        resources:
          requests:
            memory: 12Gi
          limits:
            memory: 12Gi
            cpu: 3000m
      volumes:
        - name: "docker-sock-volume"
          hostPath:
             # location on host
            path: /var/run/docker.sock
        - name: otp-data    
          hostPath:
            path: /opt/otp-data/

