---
- name: "Create {{project}}-{{ az_environment }}-aks-rg"
  command: "az group create \
    --name {{project}}-{{ az_environment }}-aks-rg \
    --location {{ az_region }}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Create {{project}}-{{ az_environment }}-aks"
  command: "az aks create \
    --resource-group {{project}}-{{ az_environment }}-aks-rg \
    --name {{project}}-{{ az_environment }}-aks \
    --node-count 12 \
    --node-vm-size Standard_F8s_v2 \
    --kubernetes-version 1.14.6 \
    --enable-addons monitoring \
    --generate-ssh-keys \
    --service-principal {{service_principal}} \
    --client-secret {{client_secret}} \
    --no-wait"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"