---
- name: "Create digitransit-{{ az_environment }}-aks-rg"
  command: "az group create \
    --name digitransit-{{ az_environment }}-aks-rg \
    --location {{ az_region }}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Create digitransit-{{ az_environment }}-aks"
  command: "az aks create \
    --resource-group digitransit-{{ az_environment }}-aks-rg \
    --name digitransit-{{ az_environment }}-aks \
    --node-count 3 \
    --node-vm-size Standard_D4s_v3 \
    --kubernetes-version 1.13.5 \
    --enable-addons monitoring \
    --generate-ssh-keys"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"