---
- name: "Create {{project}}-{{ az_environment }}-aks-rg"
  command: "az group create \
    --name {{project}}-{{ az_environment }}-aks-rg \
    --location {{ az_region }}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Create {{project}}-{{ az_environment }}-aks"
  command: "az aks create \
    --resource-group {{project}}-{{ az_environment }}-aks-rg \
    --name {{project}}-{{ az_environment }}-aks \
    --node-count 3 \
    --node-vm-size Standard_D8_v3 \
    --kubernetes-version 1.14.6 \
    --enable-addons monitoring \
    --generate-ssh-keys"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"