---
- name: "Configure kubectl to use {project}}-{{ az_environment }}-aks"
  command: "az aks get-credentials \
    --resource-group {{project}}-{{az_environment}}-aks-rg \
    --name {{project}}-{{ az_environment }}-aks"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- block:
    - name: "Apply keyvaultsecrets"
      command: "kubectl apply -f \
        {{ role_path }}/files/{{ az_environment }}/keyvaultsecrets-{{ az_environment }}.yml"
      delegate_to: localhost
      ignore_errors: "{{ ansible_check_mode }}"
      register: out

    - debug: var=out.stdout_lines
    
    - name: "Apply yleisviestipalvelu-assets"
      command: "kubectl apply -f \
        {{ role_path }}/files/assets/yleisviestipalvelu-assets.yml"
      delegate_to: localhost
      ignore_errors: "{{ ansible_check_mode }}"
      register: out

    - debug: var=out.stdout_lines
    
    - name: "Apply rest of manifests"
      command: "kubectl apply -f \
        {{ role_path }}/files/{{ az_environment }}/"
      delegate_to: localhost
      ignore_errors: "{{ ansible_check_mode }}"
      register: out

    - debug: var=out.stdout_lines
  when: service is undefined

- block:
    - name: "Apply {{ service }}"
      command: "kubectl apply -f \
        {{ role_path }}/files/{{ az_environment }}/{{ service }}-{{ az_environment }}.yml"
      delegate_to: localhost
      ignore_errors: "{{ ansible_check_mode }}"
      register: out

    - debug: var=out.stdout_lines
  when: service is defined
