---
- name: "Configure kubectl to use {{aks_name}}"
  command: "az aks get-credentials \
    --resource-group {{aks_resource_group_name}} \
    --name {{aks_name}}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- block:
    - name: "Apply keyvaultsecrets"
      command: "kubectl apply -f \
        {{ role_path }}/files/{{ az_environment }}/keyvaultsecrets-{{ az_environment }}.yml"
      delegate_to: localhost
      ignore_errors: "{{ ansible_check_mode }}"
      register: out

    - debug: var=out.stdout_lines

    - name: "Apply cluster roles"
      command: "kubectl apply -f \
        {{ role_path }}/files/cluster_roles/"
      delegate_to: localhost
      ignore_errors: "{{ ansible_check_mode }}"
      register: out

    - debug: var=out.stdout_lines

    - name: "Apply assets"
      command: "kubectl apply -f \
        {{ role_path }}/files/assets/"
      delegate_to: localhost
      ignore_errors: "{{ ansible_check_mode }}"
      register: out

    - debug: var=out.stdout_lines

    - name: "Apply rest of manifests"
      command: "kubectl apply -f \
        {{ role_path }}/files/{{ az_environment }}/"
      delegate_to: localhost
      ignore_errors: "{{ ansible_check_mode }}"
      register: out

    - debug: var=out.stdout_lines
  when: service is undefined

- block:
    - name: "Apply {{ service }}"
      command: "kubectl apply -f \
        {{ role_path }}/files/{{ az_environment }}/{{ service }}-{{ az_environment }}.yml"
      delegate_to: localhost
      ignore_errors: "{{ ansible_check_mode }}"
      register: out

    - debug: var=out.stdout_lines
  when: service is defined
