# set fixed replica count to prevent downscaling while services are offline
# kubectl apply -f fixed-pods-hpa-prod.yml

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hsl-map-server-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hsl-map-server
  minReplicas: 3
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 15
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
      - type: Percent
        value: 100
        periodSeconds: 90
    scaleDown:
      stabilizationWindowSeconds: 300 # 5 min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opentripplanner-finland-v2-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opentripplanner-finland-v2
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 2
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 300
        periodSeconds: 300
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Pods
        value: 1
        periodSeconds: 600

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opentripplanner-hsl-v2-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opentripplanner-hsl-v2
  minReplicas: 8
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 55
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
      - type: Percent
        value: 100
        periodSeconds: 90
    scaleDown:
      stabilizationWindowSeconds: 300 # 5 min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opentripplanner-kela-v2-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opentripplanner-kela-v2
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 100
        periodSeconds: 600
    scaleDown:
      stabilizationWindowSeconds: 600 # 5 min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 600


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opentripplanner-varely-v2-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opentripplanner-varely-v2
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 2
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 300
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Pods
        value: 1
        periodSeconds: 600

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opentripplanner-waltti-v2-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opentripplanner-waltti-v2
  minReplicas: 32
  maxReplicas: 32
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
      - type: Percent
        value: 100
        periodSeconds: 90
    scaleDown:
      stabilizationWindowSeconds: 300 # 5 min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pelias-api-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pelias-api
  minReplicas: 6
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
      - type: Percent
        value: 100
        periodSeconds: 90
    scaleDown:
      stabilizationWindowSeconds: 300 # 5 min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pelias-data-container-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pelias-data-container
  minReplicas: 7
  maxReplicas: 7
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 55
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
      - type: Percent
        value: 100
        periodSeconds: 90
    scaleDown:
      stabilizationWindowSeconds: 300 # 5 min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: digitransit-ui-hsl-v3-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: digitransit-ui-hsl-v3
  minReplicas: 5
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Pods
        value: 1
        periodSeconds: 600

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: digitransit-ui-matka-v3-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: digitransit-ui-matka-v3
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 3
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Pods
        value: 1
        periodSeconds: 600

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: digitransit-ui-waltti-v3-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: digitransit-ui-waltti-v3
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 3
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Pods
        value: 1
        periodSeconds: 600

----
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: digitransit-proxy-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: digitransit-proxy
  minReplicas: 8
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 15
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Pods
        value: 1
        periodSeconds: 600
