apiVersion: v1
kind: Service
metadata:
  name: digitransit-site
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-site-service-port
    protocol: TCP
  selector:
    app: digitransit-site
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-site
  labels:
    app: digitransit-site
    update: auto
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: digitransit-site
  template:
    metadata:
      labels:
        app: digitransit-site
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: digitransit-site
        image: hsldevcom/digitransit-site:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/"
        livenessProbe:
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
