apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-data-con-hsl
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-data-con-hsl-service-port
    protocol: TCP
  selector:
    app: opentripplanner-data-con-hsl
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-data-con-hsl
  labels:
    app: opentripplanner-data-con-hsl
    update: auto
spec:
  selector:
    matchLabels:
      app: opentripplanner-data-con-hsl
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: opentripplanner-data-con-hsl
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: opentripplanner-data-con-hsl
        image: hsldevcom/opentripplanner-data-container-hsl:latest
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/version.txt"
        livenessProbe:
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/version.txt"
        resources:
          requests:
            memory: "224Mi"
          limits:
            memory: "224Mi"
            cpu: "100m"  
