---
apiVersion: batch/v1
kind: Job
metadata:
  name: otp-data-builder-job-waltti-v3
spec:
  backoffLimit: 2 # max two retries
  template:
    metadata:
      labels:
        app: otp-data-builder-job-waltti-v3
    spec:
      activeDeadlineSeconds: 9000 # one build can take max 2 hours and 30 minutes
      restartPolicy: OnFailure
      nodeSelector:
        agentpool: builderpool
      tolerations:
      - key: "builder"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      containers:
      - name: otp-data-builder-job-waltti-v3
        image: hsldevcom/otp-data-builder:v3
        volumeMounts:
        - mountPath: /opt/otp-data-builder/storage
          name: datastorage
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
        env:
        - name: ROUTER_NAME
          value: "waltti"
        - name: BUILDER_TYPE
          value: "Waltti dev v3"
        - name: DOCKER_AUTH
          valueFrom:
            secretKeyRef:
              name: docker-auth
              key: docker-auth
        - name: SKIPPED_SITES
          value: "all"
        - name: DOCKER_TAG
          value: "v3"
        - name: DOCKER_USER
          valueFrom:
            secretKeyRef:
              name: docker-user
              key: docker-user
        - name: SLACK_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-access-token
              key: slack-access-token
        - name: SLACK_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: slack-ci-channel-id
              key: slack-ci-channel-id
        - name: OTP_TAG
          value: "v2"
        - name: SEED_TAG
          value: "v3"
        - name: TOOLS_TAG
          value: "v3"
        - name: SPLIT_BUILD_TYPE
          value: "NO_SPLIT_BUILD"
        resources:
          requests:
            memory: 14Gi
            cpu: 7000m
          limits:
            memory: 14Gi
            cpu: 8000m
      imagePullSecrets:
        - name: hsldevcomkey
      volumes:
        - name: "datastorage"
          nfs:
            server: digitransitdevaksstrg.file.core.windows.net
            path: /digitransitdevaksstrg/waltti
            readOnly: false

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-job-waltti-v3-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-job-waltti-v3
