apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-hsl-next
spec:
  ports:
  - port: 8088
    targetPort: 8080
    name: digitransit-ui-hsl-next-service-port
  selector:
    app: digitransit-ui-hsl-next
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-hsl-next
  labels:
    app: digitransit-ui-hsl-next
spec:
  selector:
    matchLabels:
      app: digitransit-ui-hsl-next
  replicas: 3
  template:
    metadata:
      labels:
        app: digitransit-ui-hsl-next
    spec:
      containers:
      - name: digitransit-ui-hsl-next
        image: hsldevcom/digitransit-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG
          value: "hsl"
        - name: API_URL
          value: "https://dev-api.digitransit.fi"
        - name: MAP_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net"
        - name: OTP_URL
          value: "http://test.fi/routing/v1/routers/hsl/"
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hsl-ui-next-ingress
  namespace: default
spec:
  rules:
  - host: test.fi
    http:
      paths:
      - backend:
          serviceName: digitransit-ui-hsl-next
          servicePort: 8088
        path: /