apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-hsl-next
spec:
  ports:
  - port: 1001
    targetPort: 8080
    name: digitransit-ui-hsl-next-service-port
  selector:
    app: digitransit-ui-hsl-next
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-hsl-next
  labels:
    app: digitransit-ui-hsl-next
    update: auto
spec:
  selector:
    matchLabels:
      app: digitransit-ui-hsl-next
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: digitransit-ui-hsl-next
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: digitransit-ui-hsl-next
        image: hsldevcom/digitransit-ui:prod
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 10
          failureThreshold: 3
        env:
        - name: CONFIG
          value: "hsl"
        - name: API_URL
          value: "https://api.digitransit.fi"
        # - name: ASSET_URL
        #  value: "https://digitransit-prod-cdn-origin.azureedge.net/ui/v1/hsl"
        - name: MAP_URL
          value: "https://digitransit-prod-cdn-origin.azureedge.net"
        - name: OTP_URL
          value: "http://a-api.digitransit.fi/routing/v1/routers/next-hsl/"
        - name: NODE_OPTS
          value: "--max_old_space_size=1000"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
          # Todo: PIWI and Sentry env variables
        resources:
          requests:
            memory: "1536Mi"
          limits:
            memory: "1536Mi"
