apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-hsl-next
spec:
  ports:
  - port: 8088
    targetPort: 8080
    name: digitransit-ui-hsl-next-service-port
  selector:
    app: digitransit-ui-hsl-next
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-hsl-next
  labels:
    app: digitransit-ui-hsl-next
spec:
  selector:
    matchLabels:
      app: digitransit-ui-hsl-next
  replicas: 2
  template:
    metadata:
      labels:
        app: digitransit-ui-hsl-next
    spec:
      containers:
      - name: digitransit-ui-hsl-next
        image: hsldevcom/digitransit-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG
          value: "hsl"
        - name: API_URL
          value: "https://dev-api.digitransit.fi"
        - name: MAP_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net"
        - name: OTP_URL
          value: "http://test.fi/routing/v1/routers/hsl/"
        - name: NODE_OPTS
          value: "--max_old_space_size=600"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "1Gi"
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $req_id";
      more_set_headers "something: asd";
  name: hsl-ui-next-ingress
  namespace: default
spec:
  rules:
  - host: test.fi
    http:
      paths:
      - backend:
          serviceName: digitransit-ui-hsl-next
          servicePort: 8088
        path: /
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $req_id";
      more_set_headers "something: lol";
      proxy_cache common;
      proxy_cache_valid 200 5m;
      proxy_cache_lock on;
      proxy_cache_key "$host$request_uri";
      add_header X-Proxy-Cache $upstream_cache_status;
      proxy_ignore_headers X-Accel-Expires Expires Cache-Control Set-Cookie;
      proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;
  name: hsl-ui-next-ingress-sw
  namespace: default
spec:
  rules:
  - host: test.fi
    http:
      paths:
      - backend:
          serviceName: digitransit-ui-hsl-next
          servicePort: 8088
        path: /js/929da434e89ea0a6ffcc.js