apiVersion: v1
kind: Service
metadata:
  name: hsl-timetable-container
spec:
  ports:
  - port: 10029
    targetPort: 8080
    name: hsl-timetable-container-service-port
    protocol: TCP
  selector:
    app: hsl-timetable-container
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsl-timetable-container
  labels:
    app: hsl-timetable-container
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hsl-timetable-container
  template:
    metadata:
      labels:
        app: hsl-timetable-container
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: hsl-timetable-container
        image: hsldevcom/hsl-timetable-container:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        # TODO: network: BRIDGE ??
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/version.txt"
        resources:
          requests:
            memory: "12Mi"
          limits:
            memory: "12Mi"
            cpu: "100m"
