apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-data-con-next-hsl
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-data-con-next-hsl-service-port
    protocol: TCP
  selector:
    app: opentripplanner-data-con-next-hsl
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-data-con-next-hsl
  labels:
    app: opentripplanner-data-con-next-hsl
spec:
  selector:
    matchLabels:
      app: opentripplanner-data-con-next-hsl
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: opentripplanner-data-con-next-hsl
        update: auto
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: opentripplanner-data-con-next-hsl
        image: hsldevcom/opentripplanner-data-container-hsl:prod
        # TODO: network: BRIDGE ??
        # TODO: net host ??
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/version.txt"
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "200Mi"
            cpu: "100m"  
