apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-data-con-next-waltti-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-data-con-next-waltti-service-port
  selector:
    app: opentripplanner-data-con-next-waltti
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-data-con-next-waltti
  labels:
    app: opentripplanner-data-con-next-waltti
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: opentripplanner-data-con-next-waltti
  template:
    metadata:
      labels:
        app: opentripplanner-data-con-next-waltti
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: opentripplanner-data-con-next-waltti
        image: hsldevcom/opentripplanner-data-container-waltti:prod
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        # TODO: network: BRIDGE ??
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/version.txt"
        resources:
          requests:
            memory: 200Mi
          limits:
            memory: 200Mi
            cpu: "100m"
