---
- name: "Create {{resource_group_name}}"
  command: "az group create \
    --name {{resource_group_name}} \
    --location {{az_region}} \
    --subscription {{fav_service_subscription}}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Create storage account {{storage_account_name}}"
  command: "az storage account create \
    --resource-group {{resource_group_name}} \
    --name {{storage_account_name}} \
    --location {{az_region}} \
    --sku {{storage_sku}} \
    --subscription {{fav_service_subscription}}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Create {{redis_name}}"
  command: "az redis create \
    --resource-group {{resource_group_name}} \
    --name {{redis_name}} \
    --location {{az_region}} \
    --subscription {{fav_service_subscription}} \
    --sku {{redis_sku}} \
    --vm-size {{redis_vm_size}}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Create {{service_name}}"
  command: "az functionapp create \
    --resource-group {{resource_group_name}} \
    --name {{service_name}} \
    --storage-account {{storage_account_name}} \
    --consumption-plan-location {{az_region}} \
    --functions-version {{functions_version}} \
    --os-type {{os_type}} \
    --runtime {{runtime_stack}} \
    --runtime-version {{runtime_version}} \
    --subscription {{fav_service_subscription}}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Get redis key"
  shell: az redis list-keys
    --resource-group {{resource_group_name}}
    --name {{redis_name}}
    --subscription {{fav_service_subscription}} | jq -M -j '.primaryKey'
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"
  register: redis_key

- name: Get redis hostname
  shell: az redis show
    --resource-group {{resource_group_name}}
    --name {{redis_name}}
    --subscription {{fav_service_subscription}} | jq -M -j '.hostName'
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"
  register: redis_hostname

- name: Get redis port
  shell: az redis show
    --resource-group {{resource_group_name}}
    --name {{redis_name}}
    --subscription {{fav_service_subscription}} | jq -M -j '.sslPort'
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"
  register: redis_port

- name: "Add configurations"
  command: az functionapp config appsettings set
    --resource-group {{resource_group_name}}
    --name {{service_name}}
    --subscription {{fav_service_subscription}}
    --settings
    FAVORITES_HOST={{service_name}}.azurewebsites.net
    redisHost={{redis_hostname.stdout}}
    redisPort={{redis_port.stdout}}
    redisPass={{redis_key.stdout}}
    hslIdUrl={{hslIdUrl}}
    clientId={{clientId}}
    clientCredentials="{{clientCredentials}}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"
