---
- name: "Create {{resource_group_name}}"
  command: "az group create \
    --name {{resource_group_name}} \
    --location {{az_region}}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Create storage account {{storage_account_name}}"
  command: "az storage account create \
    --resource-group {{resource_group_name}} \
    --name {{storage_account_name}} \
    --location {{az_region}} \
    --sku {{storage_sku}}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Create {{service_name}}"
  command: "az functionapp create \
    --resource-group {{resource_group_name}} \
    --name {{service_name}} \
    --storage-account {{storage_account_name}} \
    --consumption-plan-location {{az_region}} \
    --os-type {{os_type}} \
    --runtime {{runtime_stack}} \
    --runtime-version {{runtime_version}}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Assign identity"
  command: "az functionapp identity assign \
    --resource-group {{resource_group_name}} \
    --name {{service_name}} \
     --role Reader \
     --scope {{resource_id}}"
  delegate_to: localhost
  ignore_errors: "{{ ansible_check_mode }}"
