---
# Add here variables specific to DEV environment
"az_environment": "dev"
"az_environment_postfix": "2"
"node_count": "12"

"gateway_name_postfix": "3"
"gateway_capacity": "2"

"sku_name": "Developer"
