---
# Add here variables specific to the dev environment
"az_environment": "dev"

# AKS variables
"aks_environment_postfix": "5"
"aks_environment_with_postfix": "{{az_environment}}{{aks_environment_postfix}}"
"aks_name": "{{project}}-{{aks_environment_with_postfix}}-aks"
"aks_resource_group_name": "{{aks_name}}-rg"
"default_node_count": "7"
"worker_node_count": "4"
"workerv2_node_count": "8"
"addons_to_remove": "kube-dashboard"
"kubernetes_version": "1.24.3"
"default_nodepool_name": "defaultpool"
"worker_nodepool_name": "superpool"
"workerv2_nodepool_name": "megapool"
"default_labels": "pool=defaultpool"
"worker_labels": "pool=superpool"
"workerv2_labels": "pool=megapool"

# Application Gateway variables
"gateway_name_postfix": "3"
"gateway_capacity": "2"

# Api Management variables
"sku_name": "Developer"
