---
# Add here variables specific to the dev environment
"az_environment": "dev"

# AKS variables
"aks_environment_postfix": "3"
"aks_environment_with_postfix": "{{az_environment}}{{aks_environment_postfix}}"
"aks_name": "{{project}}-{{aks_environment_with_postfix}}-aks"
"aks_resource_group_name": "{{aks_name}}-rg"
"node_count": "13"
"addons_to_remove": "kube-dashboard"
"kubernetes_version": "1.18.10"

# Application Gateway variables
"gateway_name_postfix": "3"
"gateway_capacity": "2"

# Api Management variables
"sku_name": "Developer"
