---
# Add here variables specific to the prod environment
"az_environment": "prod"

# AKS variables
"aks_environment_postfix": "5"
"aks_environment_with_postfix": "{{az_environment}}{{aks_environment_postfix}}"
"aks_name": "{{project}}-{{aks_environment_with_postfix}}-aks"
"aks_resource_group_name": "{{aks_name}}-rg"
"default_node_count": "15"
"worker_node_count": "14"
"workerv2_node_count": "53"
"addons_to_add": "monitoring"
"addons_to_remove": "kube-dashboard"
"log_analytics_workspace_rg": "OMS-PROD-RG"
"kubernetes_version": "1.25.5"
"default_nodepool_name": "defaultpool"
"worker_nodepool_name": "superpool"
"workerv2_nodepool_name": "megapool"
"default_labels": "pool=defaultpool"
"worker_labels": "pool=superpool"
"workerv2_labels": "pool=megapool"

# Application Gateway variables
"gateway_name_postfix": ""
"gateway_capacity": "2"

# Api Management variables
"sku_name": "Standard"
