---
# Add here variables specific to DEV environment
"az_environment": "prod"
"az_environment_postfix": "2"
"node_count": "53"

"gateway_name_postfix": ""
"gateway_capacity": "2"

"sku_name": "Standard"

"addons": "monitoring"
"log_analytics_workspace_rg": "oms-prod-rg"

"kubernetes_version": "1.16.10"
