---
# Add here variables specific to DEV environment
"az_environment": "prod"
"az_environment_postfix": "2"
"node_count": "53"

"gateway_name_postfix": ""
"gateway_capacity": "2" 

"sku_name": "Standard"

"log_analytics_workspace": "@Microsoft.KeyVault(SecretUri=https://digitransit-dev-keyvault.vault.azure.net/secrets/prod-log-analytics-resource-id/b385ce53049748879958dd3e6f0342d6)"