---
# Add here variables specific to the prod environment
"az_environment": "prod"

# AKS variables
"aks_environment_postfix": "3"
"aks_environment_with_postfix": "{{az_environment}}{{aks_environment_postfix}}"
"aks_name": "{{project}}-{{aks_environment_with_postfix}}-aks"
"aks_resource_group_name": "{{aks_name}}-rg"
<<<<<<< HEAD
// "node_count": "67"
"default_node_count": "1"
"worker_node_count": "2"
=======
"node_count": "66"
>>>>>>> master
"addons_to_add": "monitoring"
"addons_to_remove": "kube-dashboard"
"log_analytics_workspace_rg": "OMS-PROD-RG"
"kubernetes_version": "1.18.10"
"default_nodepool_name": "defaultpool"
"worker_nodepool_name": "superpool"
"default_labels": "pool=defaultpool"
"worker_labels": "pool=superpool"

# Application Gateway variables
"gateway_name_postfix": ""
"gateway_capacity": "2"

# Api Management variables
"sku_name": "Standard"
