---
# Add here variables specific to the prod environment
"az_environment": "prod"

# AKS variables
"aks_environment_postfix": "5"
"aks_environment_with_postfix": "{{az_environment}}{{aks_environment_postfix}}"
"aks_name": "{{project}}-{{aks_environment_with_postfix}}-aks"
"aks_resource_group_name": "{{aks_name}}-rg"

# AKS node pool configurations
"system_node_count": "3"

"default_min_node_count": "0"
"default_max_node_count": "30"
"default_max_surge": "10"

"worker_min_node_count": "15"
"worker_max_node_count": "130"
"worker_max_surge": "20"

"builder_min_node_count": "0"
"builder_max_node_count": "10"
"builder_max_surge": "3"

"mega_min_node_count": "0"
"mega_max_node_count": "10"
"mega_max_surge": "3"

"addons_to_add": "monitoring"
"addons_to_remove": "kube-dashboard"
"log_analytics_workspace_rg": "OMS-PROD-RG"
"kubernetes_version": "1.32.3"

# Application Gateway variables
"gateway_name_postfix": ""
"gateway_capacity": "2"

# Api Management variables
"sku_name": "Standard"
