---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "keyvault-digitransit-ui-waltti-v3"
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "8274e895-09f9-424f-afa1-9ed7c6fc23e6"
    tenantId: "572a41dd-c389-4f0a-b256-aefd1bf149d7"
    keyvaultName: "digitransit-dev-keyvault"
    objects: |
      array:
        - |
          objectName: dev-citybike-scheduler-db-conn-string
          objectType: secret
        - |
          objectName: dev-digitransit-ui-waltti-v3-apim-key
          objectType: secret
        - |
          objectName: digitransit-subscription-key-name
          objectType: secret
  secretObjects:
    - secretName: "kv-dev-citybike-scheduler-db-conn-string"
      type: Opaque
      data:
        - objectName: dev-citybike-scheduler-db-conn-string
          key: dev-citybike-scheduler-db-conn-string
    - secretName: "kv-dev-digitransit-ui-waltti-v3-apim-key"
      type: Opaque
      data:
        - objectName: dev-digitransit-ui-waltti-v3-apim-key
          key: dev-digitransit-ui-waltti-v3-apim-key
    - secretName: "kv-digitransit-subscription-key-name"
      type: Opaque
      data:
        - objectName: digitransit-subscription-key-name
          key: digitransit-subscription-key-name
---
apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-waltti-v3
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-waltti-v3-service-port
  selector:
    app: digitransit-ui-waltti-v3
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-waltti-v3
  labels:
    app: digitransit-ui-waltti-v3
    update: auto
    restartAfterDeployments: "opentripplanner-waltti-v2"
    restartDelay: "5"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-waltti-v3
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: digitransit-ui-waltti-v3
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-ui-waltti-v3
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        agentpool: burstpool
      volumes:
        - name: keyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: keyvault-digitransit-ui-waltti-v3
      serviceAccountName: keyvault-secrets
      containers:
      - name: digitransit-ui-waltti-v3
        volumeMounts:
          - name: keyvault
            mountPath: /mnt/keyvault
            readOnly: true
        image: hsldevcom/digitransit-ui:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: API_URL
          value: "https://dev-api.digitransit.fi"
        - name: RUN_ENV
          value: "development"
        - name: ASSET_URL
          value: "https://dev-cdn.digitransit.fi/ui/v3/waltti"
        - name: MAP_URL
          value: "https://dev-cdn.digitransit.fi"
        - name: NODE_OPTS
          value: "--max_old_space_size=900"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: API_SUBSCRIPTION_QUERY_PARAMETER_NAME
          valueFrom:
            secretKeyRef:
              name: "kv-digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_HEADER_NAME
          valueFrom:
            secretKeyRef:
              name: "kv-digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: "kv-dev-digitransit-ui-waltti-v3-apim-key"
              key: "dev-digitransit-ui-waltti-v3-apim-key"
        - name: BASE_CONFIG
          value: "waltti"
        - name: CITYBIKE_DB_CONN_STRING
          valueFrom:
            secretKeyRef:
              name: kv-dev-citybike-scheduler-db-conn-string
              key: dev-citybike-scheduler-db-conn-string
        - name: CITYBIKE_DATABASE
          value: "citybike-scheduler-dev"
        - name: NOINDEX
          value: "1"
        resources:
          requests:
            memory: 500Mi
            cpu: 200m
          limits:
            memory: 1000Mi
            cpu: 400m
      imagePullSecrets:
        - name: kv-hsldevcomkey
