apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-hsl-v3
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-hsl-v3-service-port
  selector:
    app: digitransit-ui-hsl-v3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-hsl-v3
  labels:
    app: digitransit-ui-hsl-v3
    update: auto
    restartAt: "03.40_13.40"
    restartAfterDeployments: "opentripplanner-hsl-v2_hsl-timetable-container"
    restartLimitInterval: "180"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-hsl-v3
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: digitransit-ui-hsl-v3
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-ui-hsl-v3
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: smallpool
      containers:
      - name: digitransit-ui-hsl-v3
        image: hsldevcom/digitransit-ui:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /etusivu
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /etusivu
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: CONFIG
          value: "hsl"
        - name: CONTENT_DOMAIN
          value: "https://cms-test.hslfi.hsldev.com"
        - name: RUN_ENV
          value: "development"
        - name: HOSTNAME
          value: "https://next-dev.digitransit.fi"
        - name: API_URL
          value: "https://dev-api.digitransit.fi"
        - name: ASSET_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net/ui/v3/hsl"
        - name: MAP_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net"
        - name: NODE_OPTS
          value: "--max_old_space_size=1000"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: API_SUBSCRIPTION_QUERY_PARAMETER_NAME
          valueFrom:
            secretKeyRef:
              name: "digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_HEADER_NAME
          valueFrom:
            secretKeyRef:
              name: "digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: "dev-digitransit-ui-hsl-v3-apim-key"
              key: "dev-digitransit-ui-hsl-v3-apim-key"
        - name: GTM_ID
          valueFrom:
            secretKeyRef:
              name: gtm-id
              key: gtm-id
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: redis-host
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_KEY
          valueFrom:
            secretKeyRef:
              name: redis-key
              key: redis-key
        - name: NOINDEX
          value: "1"
        # - name: SENTRY_DSN
        #   valueFrom:
        #     secretKeyRef:
        #       name: sentry-dsn
        #       key: sentry-dsn
        # - name: SENTRY_SECRET_DSN
        #   valueFrom:
        #     secretKeyRef:
        #       name: sentry-secret-dsn
        #       key: sentry-secret-dsn
        - name: OIDCHOST
          value: "https://hslid-uat.cinfra.fi"
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: session-secret
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: uat-oidc-client-id
              key: uat-oidc-client-id
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: uat-oidc-client-secret
              key: uat-oidc-client-secret
        - name: CITYBIKE_DB_CONN_STRING
          valueFrom:
            secretKeyRef:
              name: dev-citybike-scheduler-db-conn-string
              key: dev-citybike-scheduler-db-conn-string
        - name: CITYBIKE_DATABASE
          value: "citybike-scheduler-dev"
        resources:
          requests:
            memory: "1536Mi"
            cpu: 600m
          limits:
            memory: "1536Mi"
            cpu: 1500m
      imagePullSecrets:
        - name: hsldevcomkey
