apiVersion: v1
kind: Service
metadata:
  name: digitransit-performance-tests
spec:
  ports:
  - port: 8080
#    targetPort: <targetPORT>
    name: digitransit-performance-tests-service-port
    protocol: TCP
  selector:
    app: digitransit-performance-tests
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-performance-tests
  labels:
    app: digitransit-performance-tests
    update: auto
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: digitransit-performance-tests
  template:
    metadata:
      labels:
        app: digitransit-performance-tests
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: defaultpool
      containers:
      - name: digitransit-performance-tests
        image: hsldevcom/digitransit-performance-tests
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        # TODO: network: BRIDGE ??
    #    readinessProbe:
    #      initialDelaySeconds: <gracePeriodSeconds>
    #      periodSeconds: <timeoutSeconds>
    #      failureThreshold: <maxConsecutiveFailures>
    #      httpGet:
    #        port: <PORT>
    #        path: </path/>
        env:
        - name: CONCURRENT_USERS
          value: "75"
        - name: FILES_AND_HEADERS
          value: "test_data_otp_external.txt --content-type 'application/graphql',test2.txt,test_data_pelias_external.txt"
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: slack-webhook
              key: slack-webhook
        - name: TEST_TIME
          value: "07:25:00"
        resources:
          requests:
            memory: "128Mi"
            cpu: "1000M"
          limits:
            memory: "128Mi"
            cpu: "1000M"
      imagePullSecrets:
        - name: hsldevcomkey
