apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-hsl
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-hsl-service-port
  selector:
    app: digitransit-ui-hsl
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-hsl
  labels:
    app: digitransit-ui-hsl
    update: auto
    restartAt: "03.20_13.20"
    restartLimitInterval: "180"
    restartAfterDeployments: "opentripplanner-hsl_hsl-timetable-container"
    restartDelay: "5"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-hsl
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: digitransit-ui-hsl
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: digitransit-ui-hsl
        image: hsldevcom/digitransit-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: CONFIG
          value: "hsl"
        - name: API_URL
          value: "https://dev-api.digitransit.fi"
        - name: ASSET_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net/ui/v1/hsl"
        - name: MAP_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net"
        - name: NODE_OPTS
          value: "--max_old_space_size=1000"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: redis-host
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_KEY
          valueFrom:
            secretKeyRef:
              name: redis-key
              key: redis-key
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-dsn
              key: sentry-dsn
        - name: SENTRY_SECRET_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-secret-dsn
              key: sentry-secret-dsn
        - name: GTM_ID
          valueFrom:
            secretKeyRef:
              name: gtm-id
              key: gtm-id
        - name: OIDC_CLIENT_CALLBACK
          value: "https://dev.reittiopas.fi/oid_callback"
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: session-secret
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oidc-client-id
              key: oidc-client-id
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-client-secret
              key: oidc-client-secret
        resources:
          requests:
            memory: "1536Mi"
            cpu: 600m
          limits:
            memory: "1536Mi"
            cpu: 2000m
