apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-hsl
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-hsl-service-port
  selector:
    app: digitransit-ui-hsl-next
