---  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digitransit-deployer
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: digitransit-deployer-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - list
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: digitransit-deployer-rolebind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: digitransit-deployer-role
subjects:
- kind: ServiceAccount
  name: digitransit-deployer
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: digitransit-deployer
spec:
  ports:
    - port: 10026
      name: digitransit-deployer-service-port
      protocol: TCP
  selector:
    app: digitransit-deployer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-deployer
  labels:
    app: digitransit-deployer
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: digitransit-deployer
  template:
    metadata:
      labels:
        app: digitransit-deployer
        lastRestartDate: dummy-value
    spec:
      serviceAccountName: digitransit-deployer
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-deployer
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: smallpool
      containers:
      - name: digitransit-deployer
        image: hsldevcom/digitransit-deployer:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: DEBUG
          value: "*"
        - name: ENVIRONMENT_TYPE
          value: "DEV"
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: slack-webhook
              key: slack-webhook
        resources:
          requests:
            memory: 252Mi
            cpu: 300m
          limits:
            memory: 252Mi
            cpu: 1000m
      imagePullSecrets:
        - name: hsldevcomkey