---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "keyvault-digitransit-deployer"
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "8274e895-09f9-424f-afa1-9ed7c6fc23e6"
    tenantId: "572a41dd-c389-4f0a-b256-aefd1bf149d7"
    keyvaultName: "digitransit-dev-keyvault"
    objects: |
      array:
        - |
          objectName: docker-auth
          objectType: secret
        - |
          objectName: docker-user
          objectType: secret
        - |
          objectName: slack-access-token
          objectType: secret
        - |
          objectName: slack-ci-channel-id
          objectType: secret
        - |
          objectName: slack-dev-monitoring-channel-id
          objectType: secret
        - |
          objectName: slack-webhook
          objectType: secret
  secretObjects:
    - secretName: "kv-docker-auth"
      type: Opaque
      data:
        - objectName: docker-auth
          key: docker-auth
    - secretName: "kv-docker-user"
      type: Opaque
      data:
        - objectName: docker-user
          key: docker-user
    - secretName: "kv-slack-access-token"
      type: Opaque
      data:
        - objectName: slack-access-token
          key: slack-access-token
    - secretName: "kv-slack-ci-channel-id"
      type: Opaque
      data:
        - objectName: slack-ci-channel-id
          key: slack-ci-channel-id
    - secretName: "kv-slack-dev-monitoring-channel-id"
      type: Opaque
      data:
        - objectName: slack-dev-monitoring-channel-id
          key: slack-dev-monitoring-channel-id
    - secretName: "kv-slack-webhook"
      type: Opaque
      data:
        - objectName: slack-webhook
          key: slack-webhook
---  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: digitransit-deployer
  namespace: default
  annotations:
    azure.workload.identity/client-id: "8274e895-09f9-424f-afa1-9ed7c6fc23e6"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: digitransit-deployer-role
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - replicasets
    verbs:
      - list
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: digitransit-deployer-rolebind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: digitransit-deployer-role
subjects:
- kind: ServiceAccount
  name: digitransit-deployer
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: digitransit-deployer
spec:
  ports:
    - port: 10026
      name: digitransit-deployer-service-port
      protocol: TCP
  selector:
    app: digitransit-deployer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-deployer
  labels:
    app: digitransit-deployer
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: digitransit-deployer
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: digitransit-deployer
    spec:
      serviceAccountName: digitransit-deployer
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-deployer
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        agentpool: burstpool
      volumes:
        - name: keyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: keyvault-digitransit-deployer
      containers:
      - name: digitransit-deployer
        volumeMounts:
          - name: keyvault
            mountPath: /mnt/keyvault
            readOnly: true
        image: hsldevcom/digitransit-deployer:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ENVIRONMENT_TYPE
          value: "DEV"
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: kv-slack-webhook
              key: slack-webhook
        - name: SLACK_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: kv-slack-access-token
              key: slack-access-token
        - name: MONITORING_SLACK_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: kv-slack-dev-monitoring-channel-id
              key: slack-dev-monitoring-channel-id
        - name: ALERT_SLACK_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: kv-slack-ci-channel-id
              key: slack-ci-channel-id
        - name: DOCKER_USER
          valueFrom:
            secretKeyRef:
              name: kv-docker-user
              key: docker-user
        - name: DOCKER_AUTH
          valueFrom:
            secretKeyRef:
              name: kv-docker-auth
              key: docker-auth
        resources:
          requests:
            memory: 252Mi
            cpu: 300m
          limits:
            memory: 252Mi
            cpu: 1000m
      imagePullSecrets:
        - name: kv-hsldevcomkey
