apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-waltti-v3
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-waltti-v3-service-port
  selector:
    app: digitransit-ui-waltti-v3
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-waltti-v3
  labels:
    app: digitransit-ui-waltti-v3
    update: auto
    restartAfterDeployments: "opentripplanner-waltti"
    restartDelay: "5"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-waltti-v3
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: digitransit-ui-waltti-v3
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-ui-waltti-v3
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: defaultpool
      containers:
      - name: digitransit-ui-waltti-v3
        image: hsldevcom/digitransit-ui:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: API_URL
          value: "https://dev-api.digitransit.fi"
        - name: RUN_ENV
          value: "development"
        - name: ASSET_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net/ui/v3/waltti"
        - name: MAP_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net"
        - name: NODE_OPTS
          value: "--max_old_space_size=900"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: API_SUBSCRIPTION_QUERY_PARAMETER_NAME
          valueFrom:
            secretKeyRef:
              name: "digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_HEADER_NAME
          valueFrom:
            secretKeyRef:
              name: "digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: "dev-digitransit-ui-waltti-v3-apim-key"
              key: "dev-digitransit-ui-waltti-v3-apim-key"
        # - name: SENTRY_DSN
        #   valueFrom:
        #     secretKeyRef:
        #       name: sentry-dsn
        #       key: sentry-dsn
        # - name: GTM_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: gtm-id
        #       key: gtm-id
        - name: BASE_CONFIG
          value: "waltti"
        # - name: REDIS_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: redis-host
        #       key: redis-host
        # - name: REDIS_PORT
        #   value: "6380"
        # - name: REDIS_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: redis-key
        #       key: redis-key
        # - name: OIDCHOST
        #   value: "https://walttiid-dev7.t5.fi"
        # - name: SESSION_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       name: session-secret
        #       key: session-secret
        # - name: OIDC_CLIENT_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name: dev-waltti-oidc-client-id
        #       key: dev-waltti-oidc-client-id
        # - name: OIDC_CLIENT_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       name: dev-waltti-oidc-client-secret
        #       key: dev-waltti-oidc-client-secret
        resources:
          requests:
            memory: 1200Mi
            cpu: 500m
          limits:
            memory: 1200Mi
            cpu: 2000m
      imagePullSecrets:
        - name: hsldevcomkey
