apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-waltti-next
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-waltti-next-service-port
  selector:
    app: digitransit-ui-waltti-next
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-waltti-next
  labels:
    app: digitransit-ui-waltti-next
    update: auto
    restartAfterDeployments: "opentripplanner-waltti"
    restartDelay: "5"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-waltti-next
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: digitransit-ui-waltti-next
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: defaultpool
      containers:
      - name: digitransit-ui-waltti-next
        image: hsldevcom/digitransit-ui:next
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: API_URL
          value: "https://dev-api.digitransit.fi"
        - name: ASSET_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net/ui/v1/waltti-next"
        - name: MAP_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net"
        - name: NODE_OPTS
          value: "--max_old_space_size=900"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-dsn
              key: sentry-dsn
        - name: GTM_ID
          valueFrom:
            secretKeyRef:
              name: gtm-id
              key: gtm-id
        - name: MAP_PATH_PREFIX
          value: "next-"
        - name: BASE_CONFIG
          value: "waltti"
        resources:
          requests:
            memory: 1200Mi
            cpu: 500m
          limits:
            memory: 1200Mi
            cpu: 2000m
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: digitransit-ui-waltti-next-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: digitransit-ui-waltti-next
