apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-hsl-next
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-hsl-next-service-port
  selector:
    app: digitransit-ui-hsl-next
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-hsl-next
  labels:
    app: digitransit-ui-hsl-next
    update: auto
    restartAt: "03.20_13.20"
    restartLimitInterval: "180"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-hsl-next
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: digitransit-ui-hsl-next
    spec:
      priorityClassName: medium-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: digitransit-ui-hsl-next
        image: hsldevcom/digitransit-ui:next
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: CONFIG
          value: "hsl"
        - name: API_URL
          value: "https://dev-api.digitransit.fi"
        - name: ASSET_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net/ui/v1/hsl-next"
        - name: MAP_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net"
        - name: NODE_OPTS
          value: "--max_old_space_size=1000"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        resources:
          requests:
            memory: "1536Mi"
            cpu: 600m
          limits:
            memory: "1536Mi"
            cpu: 2000m
