apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-linjasto2021
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-linjasto2021-service-port
  selector:
    app: digitransit-ui-linjasto2021
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-linjasto2021
  labels:
    app: digitransit-ui-linjasto2021
    update: auto
    restartAt: "03.20_13.20"
    restartLimitInterval: "180"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-linjasto2021
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: digitransit-ui-linjasto2021
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: digitransit-ui-linjasto2021
        image: hsldevcom/digitransit-ui:ratikka
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: CONFIG
          value: "linjasto2021"
        - name: HOSTNAME
          value: "https://dev-linjasto2021.digitransit.fi"
        - name: API_URL
          value: "https://dev-api.digitransit.fi"
        - name: ASSET_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net/ui/v1/linjasto2021"
        - name: MAP_URL
          value: "https://digitransit-dev-cdn-origin.azureedge.net"
        - name: NODE_OPTS
          value: "--max_old_space_size=1000"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: GTM_ID
          valueFrom:
            secretKeyRef:
              name: gtm-id
              key: gtm-id
        resources:
          requests:
            memory: "1536Mi"
            cpu: 600m
          limits:
            memory: "1536Mi"
            cpu: 2000m
      imagePullSecrets:
        - name: hsldevcomkey
