apiVersion: v1
kind: Service
metadata:
  name: graphiql
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: graphiql-service-port
    protocol: TCP
  selector:
    app: graphiql
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphiql
  labels:
    app: graphiql
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: graphiql
  template:
    metadata:
      labels:
        app: graphiql
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - graphiql
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: defaultpool
      containers:
      - name: graphiql
        image: hsldevcom/graphiql
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/graphiql/hsl"
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/graphiql/hsl"
        env: 
        - name: REACT_APP_API_SUBSCRIPTION_KEY_PARAM  
          valueFrom:
            secretKeyRef:
              name: "digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: REACT_APP_API_SUBSCRIPTION_KEY
          valueFrom:
            secretKeyRef:
              name: "dev-graphiql-apim-key"
              key: "dev-graphiql-apim-key"   
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: hsldevcomkey
