---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hsl-timetable-builder
spec:
  schedule: "13 3 * * *" # schedule in UTC time
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: hsl-timetable-builder
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 9000 # one build can take max 2 hours and 30 minutes
          restartPolicy: OnFailure
          nodeSelector:
            pool: defaultpool
          containers:
          - name: hsl-timetable-builder
            image: hsldevcom/hsl-timetable-builder:latest
            volumeMounts:
              - mountPath: /var/run/docker.sock
                name: "docker-sock-volume"
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
            env:
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: DOCKER_TAG
              value: "latest"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: FONTSTACK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fontstack-password
                  key: fontstack-password
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook
                  key: slack-webhook
            - name: TAKU_API_URL
              valueFrom:
                secretKeyRef:
                  name: taku-api
                  key: taku-api
            - name: TAKU_KEY
              valueFrom:
                secretKeyRef:
                  name: taku-key
                  key: taku-key
            - name: TIMETABLE_DAYS_ADVANCE
              value: "2"
            - name: BUILD_INTERVAL
              value: "-1" # don't run build in a loop
            resources:
              requests:
                memory: 2736Mi
                cpu: 1000m
              limits:
                memory: 2736Mi
                cpu: 4000m
          imagePullSecrets:
            - name: hsldevcomkey
          volumes:
            - name: "docker-sock-volume"
              hostPath:
                # location on host
                path: /var/run/docker.sock

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: hsl-timetable-builder-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hsl-timetable-builder
