---
# Used by every workload that mounts its own SecretProviderClass.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keyvault-secrets
  namespace: default
  annotations:
    azure.workload.identity/client-id: "8274e895-09f9-424f-afa1-9ed7c6fc23e6"
