apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-finland
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-finland-service-port
  selector:
    app: opentripplanner-finland
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-finland
  labels:
    app: opentripplanner-finland
    update: auto
    restartDelay: "1"
    restartAt: "05.15"
    restartLimitInterval: "720"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: opentripplanner-finland
  template:
    metadata:
      labels:
        app: opentripplanner-finland
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      nodeSelector:
        agentpool: userpooltest
      tolerations:
      - key: "testingPod"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      containers:
      - name: opentripplanner-finland
        image: hsldevcom/opentripplanner:v1-finland
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: datastorage
            mountPath: /var/otp/
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/routers/finland/"
        startupProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 18
          httpGet:
            port: 8080
            path: "/otp/routers/finland/"
        livenessProbe:
          periodSeconds: 120
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/otp/routers/finland/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: JAVA_OPTS
          value: -XX:+UseParNewGC -Xms10G -Xmx10G -XX:NewRatio=5 -XX:+UseStringDeduplication
        resources:
          requests:
            memory: "11Gi"
            cpu: "3000m"
          limits:
            memory: "11Gi"
            cpu: "4000m"
      imagePullSecrets:
        - name: hsldevcomkey
      volumes:
      - name: "datastorage"
        persistentVolumeClaim:
          claimName: otp-data-finland-v2-pvc
          readOnly: true
