apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-hsl
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-hsl-service-port
  selector:
    app: opentripplanner-hsl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-hsl
  labels:
    app: opentripplanner-hsl
    update: auto
    restartAfterDeployments: "opentripplanner-data-con-hsl"
    restartDelay: "1"
    restartAt: "05.15"
    restartLimitInterval: "720"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: opentripplanner-hsl
  template:
    metadata:
      labels:
        app: opentripplanner-hsl
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      nodeSelector:
        agentpool: userpooltest
      tolerations:
      - key: "testingPod"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      containers:
      - name: opentripplanner-hsl
        image: hsldevcom/opentripplanner:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/routers/hsl/"
        startupProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 120
          httpGet:
            port: 8080
            path: "/otp/routers/hsl/"
        livenessProbe:
          periodSeconds: 120
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/otp/routers/hsl/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ROUTER_DATA_CONTAINER_URL
          value: "http://opentripplanner-data-con-hsl:8080"
        - name: ROUTER_NAME
          value: "hsl"
        - name: JAVA_OPTS
          value: -XX:+UseParNewGC -Xms10G -Xmx10G -XX:NewRatio=5 -XX:+UseStringDeduplication
        resources:
          requests:
            memory: "11Gi"
            cpu: "3000m"
          limits:
            memory: "11Gi"
            cpu: "4000m"
      imagePullSecrets:
        - name: hsldevcomkey

