apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-waltti
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-waltti-service-port
  selector:
    app: opentripplanner-waltti

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-waltti
  labels:
    app: opentripplanner-waltti
    update: auto
    restartAfterDeployments: "opentripplanner-data-con-waltti"
    restartDelay: "1"
    restartAt: "05.45"
    restartLimitInterval: "720"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: opentripplanner-waltti
  template:
    metadata:
      labels:
        app: opentripplanner-waltti
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      nodeSelector:
        pool: superpool
      containers:
      - name: opentripplanner-waltti
        image: hsldevcom/opentripplanner:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/routers/waltti/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ROUTER_DATA_CONTAINER_URL
          value: "http://opentripplanner-data-con-waltti:8080"
        - name: ROUTER_NAME
          value: "waltti"
        - name: JAVA_OPTS
          valueFrom:
            secretKeyRef:
              name: otp-waltti-java-opts-dev
              key: otp-waltti-java-opts-dev
        resources:
          requests:
            memory: 12Gi
            cpu: "7000m"
          limits:
            memory: 12Gi
            cpu: "8000m"
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opentripplanner-waltti-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: opentripplanner-waltti
