---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "keyvault-opentripplanner-finland-v2"
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "8274e895-09f9-424f-afa1-9ed7c6fc23e6"
    tenantId: "572a41dd-c389-4f0a-b256-aefd1bf149d7"
    keyvaultName: "digitransit-dev-keyvault"
    objects: |
      array:
        - |
          objectName: mobility-api-key
          objectType: secret
  secretObjects:
    - secretName: "kv-mobility-api-key"
      type: Opaque
      data:
        - objectName: mobility-api-key
          key: mobility-api-key
---
apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-finland-v2
  labels:
    app: opentripplanner-finland-v2
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-finland-v2-service-port
  selector:
    app: opentripplanner-finland-v2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-finland-v2
  labels:
    app: opentripplanner-finland-v2
    update: auto
    restartDelay: "1"
    restartAt: "03.00"
    restartLimitInterval: "720"
    checkImageFreshnessAt: "09.00"
    imageFreshnessTitle: "Finland_routing_data"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: opentripplanner-finland-v2
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: opentripplanner-finland-v2
    spec:
      nodeSelector:
        agentpool: turinpool
      tolerations:
      - key: "turinPod"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      serviceAccountName: keyvault-secrets
      containers:
      - name: opentripplanner-finland-v2
        image: hsldevcom/opentripplanner:v2-finland
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: keyvault
            mountPath: /mnt/keyvault
            readOnly: true
          - name: otpcfgmap
            mountPath: /logback-include-extensions.xml
            subPath: file-from-cfgmap
          - name: datastorage
            mountPath: /var/otp/
        startupProbe:
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 80
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        livenessProbe:
          periodSeconds: 12
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: MOBILITY_API_KEY
          valueFrom:
            secretKeyRef:
              name: kv-mobility-api-key
              key: mobility-api-key
        - name: JAVA_OPTS
          value: "-Xmx24G -Xms24G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1ReservePercent=10 -Xlog:gc -XX:+UnlockExperimentalVMOptions -XX:+UseCompactObjectHeaders"
        resources:
          requests:
            memory: "26Gi"
            cpu: "7000m"
          limits:
            memory: "26Gi"
            cpu: "8000m"
      volumes:
      - name: keyvault
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: keyvault-opentripplanner-finland-v2
      - name: otpcfgmap
        configMap:
          name: opentripplanner-cfgmap
      - name: "datastorage"
        nfs:
          server: digitransitdevaksstrg.file.core.windows.net
          path: /digitransitdevaksstrg/finland
          readOnly: true
      imagePullSecrets:
        - name: kv-hsldevcomkey
