apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-hsl
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-hsl-service-port
  selector:
    app: opentripplanner-hsl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-hsl
  labels:
    app: opentripplanner-hsl
    update: auto
    restartDelay: "1"
    restartAt: "05.15"
    restartLimitInterval: "720"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: opentripplanner-hsl
  template:
    metadata:
      labels:
        app: opentripplanner-hsl
    spec:
      nodeSelector:
        agentpool: powerpool
      tolerations:
      - key: "powerPod"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      containers:
      - name: opentripplanner-hsl
        image: hsldevcom/opentripplanner:v1-hsl
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: datastorage
            mountPath: /var/otp/
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/routers/hsl/"
        startupProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 18
          httpGet:
            port: 8080
            path: "/otp/routers/hsl/"
        livenessProbe:
          periodSeconds: 120
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/otp/routers/hsl/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: JAVA_OPTS
          value: -XX:+UseParNewGC -Xms11G -Xmx11G -XX:NewRatio=5 -XX:+UseStringDeduplication
        resources:
          requests:
            memory: "12Gi"
            cpu: "3000m"
          limits:
            memory: "12Gi"
            cpu: "4000m"
      imagePullSecrets:
        - name: hsldevcomkey
      volumes:
      - name: "datastorage"
        nfs:
          server: digitransitdevaksstrg.file.core.windows.net
          path: /digitransitdevaksstrg/hsl
          readOnly: true

