apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-hsl-v2
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-hsl-v2-service-port
  selector:
    app: opentripplanner-hsl-v2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-hsl-v2
  labels:
    app: opentripplanner-hsl-v2
    update: auto
    restartAfterDeployments: "opentripplanner-data-con-hsl-v3"
    restartDelay: "1"
    restartAt: "03.00"
    restartLimitInterval: "720"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: opentripplanner-hsl-v2
  template:
    metadata:
      labels:
        app: opentripplanner-hsl-v2
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      nodeSelector:
        pool: superpool
      containers:
      - name: opentripplanner-hsl-v2
        image: hsldevcom/opentripplanner:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: otpcfgmap
            mountPath: /opt/opentripplanner/logback-include-extensions.xml
            subPath: file-from-cfgmap
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        startupProbe:
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 270
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        livenessProbe:
          periodSeconds: 12
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ROUTER_DATA_CONTAINER_URL
          value: "http://opentripplanner-data-con-hsl-v3:8080"
        - name: ROUTER_NAME
          value: "hsl"
        - name: JAVA_OPTS
          valueFrom:
            secretKeyRef:
              name: otp-hsl-v2-java-opts-dev
              key: otp-hsl-v2-java-opts-dev
        resources:
          requests:
            memory: "10Gi"
            cpu: "3000m"
          limits:
            memory: "10Gi"
            cpu: "8000m"
      volumes:
      - name: otpcfgmap
        configMap:
          name: opentripplanner-cfgmap
      imagePullSecrets:
        - name: hsldevcomkey
