apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-data-con-finland
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-data-con-finland-service-port
  selector:
    app: opentripplanner-data-con-finland
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-data-con-finland
  labels:
    app: opentripplanner-data-con-finland
    update: auto
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: opentripplanner-data-con-finland
  template:
    metadata:
      labels:
        app: opentripplanner-data-con-finland
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: superpool
      containers:
      - name: opentripplanner-data-con-finland
        image: hsldevcom/opentripplanner-data-container-finland:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/version.txt"
        livenessProbe:
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/version.txt"
        resources:
          requests:
            memory: "174Mi"
            cpu: "100m"
          limits:
            memory: "174Mi"
            cpu: "200m"
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: opentripplanner-data-con-finland-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: opentripplanner-data-con-finland
