apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-varely-v2
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-varely-v2-service-port
  selector:
    app: opentripplanner-varely-v2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-varely-v2
  labels:
    app: opentripplanner-varely-v2
    update: auto
    restartDelay: "1"
    restartAt: "03.00"
    restartLimitInterval: "720"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: opentripplanner-varely-v2
  template:
    metadata:
      labels:
        app: opentripplanner-varely-v2
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      nodeSelector:
        agentpool: powerpool
      tolerations:
      - key: "powerPod"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      containers:
      - name: opentripplanner-varely-v2
        image: hsldevcom/opentripplanner:v2-varely
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: otpcfgmap
            mountPath: /logback-include-extensions.xml
            subPath: file-from-cfgmap
          - name: datastorage
            mountPath: /var/otp/
        startupProbe:
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        livenessProbe:
          periodSeconds: 12
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: JAVA_OPTS
          value: "-Xmx8G -Xms8G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1ReservePercent=10  -Xlog:gc"
        resources:
          requests:
            memory: "10Gi"
            cpu: "2000m"
          limits:
            memory: "10Gi"
            cpu: "4000m"
      volumes:
      - name: otpcfgmap
        configMap:
          name: opentripplanner-cfgmap
      - name: "datastorage"
        persistentVolumeClaim:
          claimName: otp-data-varely-v3-pvc
          readOnly: true
      imagePullSecrets:
        - name: hsldevcomkey
