apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-finland
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-finland-service-port
  selector:
    app: opentripplanner-finland

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-finland
  labels:
    app: opentripplanner-finland
    update: auto
    restartAfterDeployments: "opentripplanner-data-con-finland"
    restartDelay: "1"
    restartAt: "05.30"
    restartLimitInterval: "720"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: opentripplanner-finland
  template:
    metadata:
      labels:
        app: opentripplanner-finland
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      containers:
      - name: opentripplanner-finland
        image: hsldevcom/opentripplanner:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 15
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/routers/finland/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ROUTER_DATA_CONTAINER_URL
          value: "http://opentripplanner-data-con-finland:8080"
        - name: ROUTER_NAME
          value: "finland"
        - name: JAVA_OPTS
          valueFrom:
            secretKeyRef:
              name: otp-finland-java-opts-dev
              key: otp-finland-java-opts-dev
        resources:
          requests:
            memory: 11216Mi
            cpu: "7000m"
          limits:
            memory: 11216Mi
            cpu: "7600m"
