apiVersion: v1
kind: ConfigMap
metadata:
  name: opentripplanner-cfgmap
data:
  file-from-cfgmap: |
    <included>
      <logger name="org.opentripplanner.updater.stoptime.TimetableSnapshotSource" level="error"/>
    </included>
