apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-next-waltti
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-next-waltti-service-port
  selector:
    app: opentripplanner-waltti-alt-v2

---
apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-waltti-alt-v2
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-waltti-alt-v2-service-port
  selector:
    app: opentripplanner-waltti-alt-v2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-waltti-alt-v2
  labels:
    app: opentripplanner-waltti-alt-v2
    update: auto
    restartAfterDeployments: "opentripplanner-data-con-waltti-alt-v3"
    restartDelay: "1"
    restartAt: "04.45"
    restartLimitInterval: "720"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: opentripplanner-waltti-alt-v2
  template:
    metadata:
      labels:
        app: opentripplanner-waltti-alt-v2
        lastRestartDate: dummy-value
    spec:
      priorityClassName: medium-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - opentripplanner-waltti-alt-v2
                  - opentripplanner-kela-v2
                  - pelias-api
                  - pelias-data-container
              topologyKey: kubernetes.io/hostname
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - opentripplanner-varely-v2
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: megapool
      containers:
      - name: opentripplanner-waltti-alt-v2
        image: hsldevcom/opentripplanner:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: otpcfgmap
            mountPath: /opt/opentripplanner/logback-include-extensions.xml
            subPath: file-from-cfgmap
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        startupProbe:
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 480
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        livenessProbe:
          periodSeconds: 12
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/otp/actuators/health"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ROUTER_DATA_CONTAINER_URL
          value: "http://opentripplanner-data-con-waltti-alt-v3:8080"
        - name: ROUTER_NAME
          value: "waltti-alt"
        - name: JAVA_OPTS
          value: -Xmx8728m -Xms8728m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1ReservePercent=10  -Xlog:gc
        resources:
          requests:
            memory: "10Gi"
            cpu: "3000m"
          limits:
            memory: "10Gi"
            cpu: "7000m"
      volumes:
      - name: otpcfgmap
        configMap:
          name: opentripplanner-cfgmap
      imagePullSecrets:
        - name: hsldevcomkey
