---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-data-builder-finland-dev-v3
spec:
  schedule: "50 7 * * *" # schedule in UTC time
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-data-builder-finland-dev-v3
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 9000 # one build can take max 2 hours and 30 minutes
          restartPolicy: OnFailure
          nodeSelector:
            pool: megapool
          containers:
          - name: otp-data-builder-finland-dev-v3
            image: hsldevcom/otp-data-builder:v3
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: ROUTER_NAME
              value: "finland"
            - name: BUILDER_TYPE
              value: "Finland dev v3"
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: DOCKER_TAG
              value: "v3"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: SLACK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-access-token
                  key: slack-access-token
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slack-ci-channel-id
                  key: slack-ci-channel-id
            - name: OTP_TAG
              value: "v2"
            - name: ROUTERS
              value: "finland"
            - name: SEED_TAG
              value: "v3"
            - name: TOOLS_TAG
              value: "v3"
            - name: SLACK_CHANNEL
              value: "topic-ci-otp2"
            resources:
              requests:
                memory: 11Gi
                cpu: 3000m
              limits:
                memory: 11Gi
                cpu: 6000m
          imagePullSecrets:
            - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-finland-dev-v3-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-finland-dev-v3
