---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-data-builder-hsl-dev-v3
spec:
  schedule: "30 1 * * *" # schedule in Finland time
  timeZone: "Europe/Helsinki"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-data-builder-hsl-dev-v3
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 9000 # one build can take max 2 hours and 30 minutes
          restartPolicy: OnFailure
          nodeSelector:
            pool: megapool
          containers:
          - name: otp-data-builder-hsl-dev-v3
            image: hsldevcom/otp-data-builder:v3
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: ROUTER_NAME
              value: "hsl"
            - name: BUILDER_TYPE
              value: "HSL dev v3"
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: EXTRA_SRC
              value: "{\"HSL\": {\"url\": \"https://gtfsdata.blob.core.windows.net/hsl/hsl.zip\", \"routers\": [\"hsl\"]}}"
            - name: EXTRA_UPDATERS
              value: "{\"hsl-trip-updates\": {\"topic\": \"gtfsrt/dev/fi/hsl/tu\", \"url\": \"tcp://test91.rt.hsl.fi\", \"routers\": [\"hsl\"]}, \"liipi\": {\"facilitiesUrl\": \"http://digitransit-proxy:8080/out/test.liipi.hsldev.com/api/v1/facilities.json?limit=-1\", \"utilizationsUrl\": \"http://digitransit-proxy:8080/out/test.liipi.hsldev.com/api/v1/utilizations.json?limit=-1\", \"hubsUrl\": \"http://digitransit-proxy:8080/out/test.liipi.hsldev.com/api/v1/hubs.json?limit=-1\", \"routers\": [\"hsl\"]}}"
            - name: DOCKER_TAG
              value: "v3"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: SLACK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-access-token
                  key: slack-access-token
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slack-ci-channel-id
                  key: slack-ci-channel-id
            - name: OTP_TAG
              value: "v2"
            - name: ROUTERS
              value: "hsl"
            - name: SEED_TAG
              value: "v3"
            - name: TOOLS_TAG
              value: "v3"
            - name: SLACK_CHANNEL
              value: "topic-ci-otp2"
            - name: DISABLE_BLOB_VALIDATION
              value: "true"
            resources:
              requests:
                memory: 11Gi
                cpu: 3000m
              limits:
                memory: 11Gi
                cpu: 6000m
          imagePullSecrets:
            - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-hsl-dev-v3-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-hsl-dev-v3
