---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-data-builder-waltti-v3
spec:
  schedule: "50 23 * * *" # schedule in Finland time
  timeZone: "Europe/Helsinki"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-data-builder-waltti-v3
        spec:
          activeDeadlineSeconds: 9000 # one build can take max 2 hours and 30 minutes
          restartPolicy: OnFailure
          nodeSelector:
            agentpool: builderpool
          tolerations:
          - key: "builder"
            operator: "Equal"
            value: "yes"
            effect: "NoSchedule"
          containers:
          - name: otp-data-builder-waltti-v3
            image: hsldevcom/otp-data-builder:v3
            volumeMounts:
            - mountPath: /opt/otp-data-builder/storage
              name: datastorage
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: ROUTER_NAME
              value: "waltti"
            - name: BUILDER_TYPE
              value: "Waltti dev v3"
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: EXTRA_SRC
              value: "{\"TurkuTest\": {\"url\": \"https://gtfsdata.blob.core.windows.net/turku/GTFS-TRIPS_4bd95466_2024-09-25-06-36-32.zip\"}}"
            - name: EXTRA_UPDATERS
              value: "{\"tampere-alerts\": {\"url\": \"http://digitransit-proxy:8080/out/nysse.mattersoft.fi/api/gtfsrealtime/v1.0/feed/servicealert\"}, \"tampere-trip-updates\": {\"url\": \"https://gtfsrt.blob.core.windows.net/lmj/tripupdate\"}}"
            - name: SKIPPED_SITES
              value: "kuopio.digitransit.fi"
            - name: DOCKER_TAG
              value: "v3"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: SLACK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-access-token
                  key: slack-access-token
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slack-ci-channel-id
                  key: slack-ci-channel-id
            - name: OTP_TAG
              value: "v2"
            - name: SEED_TAG
              value: "v3"
            - name: TOOLS_TAG
              value: "v3"
            resources:
              requests:
                memory: 14Gi
                cpu: 7000m
              limits:
                memory: 14Gi
                cpu: 8000m
          imagePullSecrets:
            - name: hsldevcomkey
          volumes:
            - name: "datastorage"
              persistentVolumeClaim:
                claimName: otp-data-builder-waltti-v3-pvc

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-waltti-v3-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-waltti-v3
