---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-data-builder-waltti-dev
spec:
  schedule: "40 16 * * *" # schedule in UTC time
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-data-builder-waltti-dev
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 7200 # one build can take max 2 hours
          restartPolicy: OnFailure
          nodeSelector:
            pool: megapool
          containers:
          - name: otp-data-builder-waltti-dev
            image: hsldevcom/otp-data-builder:latest
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: BUILDER_TYPE
              value: "Waltti dev"
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: DOCKER_TAG
              value: "latest"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: EXTRA_UPDATERS
              value: "{\"foli-alerts\": {\"url\": \"https://foli-beta.nanona.fi/gtfs-rt/reittiopas\", \"routers\": [\"waltti\"]}}"
            - name: SKIPPED_SITES
              value: "turku.digitransit.fi"
            - name: OTP_TAG
              value: "latest"
            - name: ROUTERS
              value: "waltti"
            - name: SEED_TAG
              value: "latest"
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook
                  key: slack-webhook
            - name: TOOLS_TAG
              value: "latest"
            resources:
              requests:
                memory: 11Gi
                cpu: 3000m
              limits:
                memory: 11Gi
                cpu: 6000m
          imagePullSecrets:
            - name: hsldevcomkey
---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-waltti-dev-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-waltti-dev
