---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-data-builder-hsl-dev
spec:
  schedule: "15 19 * * *" # schedule in Finland time
  timeZone: "Europe/Helsinki"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-data-builder-hsl-dev
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 3600 # one build can take max 1 hour
          restartPolicy: OnFailure
          nodeSelector:
            agentpool: userpooltest
          tolerations:
          - key: "testingPod"
            operator: "Equal"
            value: "yes"
            effect: "NoSchedule"
          containers:
          - name: otp-data-builder-hsl-dev
            image: hsldevcom/otp-data-builder:latest
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            imagePullPolicy: Always
            env:
            - name: BUILDER_TYPE
              value: "HSL dev"
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: DOCKER_TAG
              value: "latest"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: SLACK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-access-token
                  key: slack-access-token
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slack-ci-channel-id
                  key: slack-ci-channel-id
            - name: EXTRA_UPDATERS
              value: "{\"hsl-trip-updates\": {\"topic\": \"gtfsrt/dev/fi/hsl/tu\", \"url\": \"tcp://test91.rt.hsl.fi\", \"routers\": [\"hsl\"]}, \"hsl-bike-park\": {\"url\": \"http://digitransit-proxy:8080/out/test.liipi.hsldev.com/api/v1/facilities.json?limit=-1\", \"routers\": [\"hsl\"]}, \"hsl-car-park\": {\"url\": \"http://digitransit-proxy:8080/out/test.liipi.hsldev.com/api/v1/facilities.json?limit=-1\", \"routers\": [\"hsl\"]}, \"hsl-alerts\": {\"url\": \"https://transitdatadev.blob.core.windows.net/service-alerts/v2/hsl\", \"routers\": [\"hsl\"]}}"
            - name: OTP_TAG
              value: "latest"
            - name: ROUTERS
              value: "hsl"
            - name: SEED_TAG
              value: "latest"
            - name: TOOLS_TAG
              value: "latest"
            - name: SKIPPED_SITES
              value: "all"
            resources:
              requests:
                memory: 11776Mi
                cpu: 3000m
              limits:
                memory: 11776Mi
                cpu: 4000m
          imagePullSecrets:
            - name: hsldevcomkey
---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-hsl-dev-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-hsl-dev
