---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-data-builder-finland-dev-v3
spec:
  schedule: "50 7 * * *" # schedule in UTC time
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-data-builder-finland-dev-v3
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 9000 # one build can take max 2 hours and 30 minutes
          restartPolicy: OnFailure
          nodeSelector:
            pool: superpool
          containers:
          - name: otp-data-builder-finland-dev-v3
            image: hsldevcom/otp-data-builder:v3
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: ROUTER_NAME
              value: "finland"
            - name: BUILDER_TYPE
              value: "Finland dev v3"
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: EXTRA_SRC
              value: "{\"tampere\": {\"url\": \"http://ekstrat.tampere.fi/ekstrat/ptdata/tamperefeed.zip\", \"routers\": [\"finland\"]}, \"MATKA\": {\"url\": \"https://testikoontikartta.navici.com/tiedostot/gtfs_digitransit.zip\", \"rules\": [\"router-finland/gtfs-rules/matka-cleaned.rule\"], \"routers\": [\"finland\"]}, \"FOLI\": {\"url\": \"http://data.foli.fi/gtfs/gtfs.zip\", \"fit\": false, \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"routers\": [\"finland\"]}, \"Kuopio\": {\"url\": \"http://karttapalvelu.kuopio.fi/google_transit/google_transit.zip\", \"fit\": false, \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"routers\": [\"finland\"]}, \"Lahti\": {\"url\": \"https://tvv.fra1.digitaloceanspaces.com/223.zip\", \"fit\": \"gtfs_shape_mapfit/fit_gtfs_stops.bash\", \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"routers\": [\"finland\"]}, \"Vaasa\": {\"url\": \"https://tvv.fra1.digitaloceanspaces.com/249.zip\", \"fit\": \"gtfs_shape_mapfit/fit_gtfs_stops.bash\", \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"replacements\": {\"translations.txt\": null}, \"routers\": [\"finland\"]}, \"Joensuu\": {\"url\": \"https://tvv.fra1.digitaloceanspaces.com/207.zip\", \"fit\": \"gtfs_shape_mapfit/fit_gtfs_stops.bash\", \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"replacements\": {\"translations.txt\": null}, \"routers\": [\"finland\"]}, \"Hameenlinna\": {\"url\": \"https://tvv.fra1.digitaloceanspaces.com/203.zip\", \"fit\": \"gtfs_shape_mapfit/fit_gtfs_stops.bash\", \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"routers\": [\"finland\"]}, \"Lappeenranta\": {\"url\": \"https://tvv.fra1.digitaloceanspaces.com/225.zip\", \"fit\": \"gtfs_shape_mapfit/fit_gtfs_stops.bash\", \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"routers\": [\"finland\"]}, \"Kotka\": {\"url\": \"https://tvv.fra1.digitaloceanspaces.com/217.zip\", \"fit\": \"gtfs_shape_mapfit/fit_gtfs_stops.bash\", \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"routers\": [\"finland\"]}, \"Kouvola\": {\"url\": \"https://tvv.fra1.digitaloceanspaces.com/219.zip\", \"fit\": \"gtfs_shape_mapfit/fit_gtfs_stops.bash\", \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"routers\": [\"finland\"]}, \"Rovaniemi\": {\"url\": \"https://tvv.fra1.digitaloceanspaces.com/237.zip\", \"fit\": \"gtfs_shape_mapfit/fit_gtfs_stops.bash\", \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"routers\": [\"finland\"]}, \"Mikkeli\": {\"url\": \"https://tvv.fra1.digitaloceanspaces.com/227.zip\", \"fit\": \"gtfs_shape_mapfit/fit_gtfs_stops.bash\", \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"replacements\": {\"translations.txt\": null}, \"routers\": [\"finland\"]}, \"Kajaani\": {\"url\": \"https://tvv.fra1.digitaloceanspaces.com/211.zip\", \"fit\": \"gtfs_shape_mapfit/fit_gtfs_stops.bash\", \"rules\": [\"router-waltti/gtfs-rules/waltti.rule\"], \"replacements\": {\"translations.txt\": null}, \"routers\": [\"finland\"]}}"
            - name: EXTRA_UPDATERS
              value: "{\"hsl-trip-updates\": {\"topic\": \"gtfsrt/dev/fi/hsl/tu\", \"url\": \"tcp://test91.rt.hsl.fi\", \"routers\": [\"finland\"]}, \"hsl-alerts\": {\"url\": \"https://dev-api.digitransit.fi/realtime/service-alerts/v2/hsl\", \"routers\": [\"finland\"]}, \"tampere-trip-updates\": {\"url\": \"https://gtfsrt.blob.core.windows.net/lmj/tripupdate\", \"routers\": [\"finland\"]}}"
            - name: DOCKER_TAG
              value: "v3"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: OTP_TAG
              value: "v2"
            - name: ROUTERS
              value: "finland"
            - name: SEED_TAG
              value: "v3"
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook
                  key: slack-webhook
            - name: TOOLS_TAG
              value: "v3"
            - name: SLACK_CHANNEL
              value: "topic-ci-otp2"
            resources:
              requests:
                memory: 11Gi
                cpu: 3000m
              limits:
                memory: 11Gi
                cpu: 6000m
          imagePullSecrets:
            - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-finland-dev-v3-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-finland-dev-v3
