---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-data-builder-finland-dev
spec:
  schedule: "0 15 * * *"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-data-builder-finland-dev
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 5400 # one build can take max 1.5 hours
          restartPolicy: OnFailure
          nodeSelector:
            pool: superpool
          containers:
          - name: otp-data-builder-finland-dev
            image: hsldevcom/otp-data-builder:latest
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: BUILDER_TYPE
              value: "Finland dev"
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: DOCKER_TAG
              value: "latest"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: EXTRA_SRC
              value: "{\"HSL\": {\"remove\": true, \"routers\": [\"finland\"]}, \"MATKA\": {\"remove\": true, \"routers\": [\"finland\"]}, \"tampere\": {\"remove\": true, \"routers\": [\"finland\"]}, \"LINKKI\": {\"remove\": true, \"routers\": [\"finland\"]}, \"lautta\": {\"remove\": true, \"routers\": [\"finland\"]}, \"OULU\": {\"remove\": true, \"routers\": [\"finland\"]}, \"digitraffic\": {\"remove\": true, \"routers\": [\"finland\"]}, \"fintraffic\": {\"url\": \"https://gtfs.perille.fi/fintraffic/pilot/fintraffic-latest-gtfs.zip\", \"fit\": false, \"routers\": [\"finland\"]}}"
            - name: EXTRA_UPDATERS
              value: "{\"hsl-trip-updates\": {\"topic\": \"gtfsrt/dev/fi/hsl/tu\", \"url\": \"tcp://test91.rt.hsl.fi\", \"routers\": [\"finland\"]}, \"hsl-alerts\": {\"url\": \"https://dev-api.digitransit.fi/realtime/service-alerts/v2/hsl\", \"routers\": [\"finland\"]}, \"tampere-trip-updates\": {\"url\": \"https://gtfsrt.blob.core.windows.net/lmj/tripupdate\", \"routers\": [\"finland\"]}, \"hsl-car-park\": {\"url\": \"http://digitransit-proxy:8080/out/test.liipi.hsldev.com/api/v1/facilities.json?limit=-1\", \"type\": \"car-park\", \"sourceType\": \"hsl-parkandride\",  \"frequencySec\": 600, \"routers\": [\"finland\"]}, \"hsl-bike-park\": {\"url\": \"http://digitransit-proxy:8080/out/test.liipi.hsldev.com/api/v1/facilities.json?limit=-1\", \"type\": \"bike-park\", \"sourceType\": \"hsl-parkandride\",  \"frequencySec\": 600, \"routers\": [\"finland\"]}}"
            - name: OTP_TAG
              value: "latest"
            - name: ROUTERS
              value: "finland"
            - name: SEED_TAG
              value: "latest"
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook
                  key: slack-webhook
            - name: TOOLS_TAG
              value: "latest"
            - name: SKIPPED_SITES
              value: "opas.matka.fi"
            resources:
              requests:
                memory: 11Gi
                cpu: 3000m
              limits:
                memory: 11Gi
                cpu: 6000m
          imagePullSecrets:
            - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-finland-dev-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-finland-dev
