---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-data-builder-finland-prod
spec:
  schedule: "40 1 * * *" # schedule in UTC time
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-data-builder-finland-prod
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 9000 # one build can take max 2 hours and 30 minutes
          restartPolicy: OnFailure
          nodeSelector:
            pool: superpool
          containers:
          - name: otp-data-builder-finland-prod
            image: hsldevcom/otp-data-builder:prod
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: BUILDER_TYPE
              value: "Finland prod"
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: DOCKER_TAG
              value: "prod"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: OTP_TAG
              value: "prod"
            - name: ROUTERS
              value: "finland"
            - name: SEED_TAG
              value: "prod"
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook
                  key: slack-webhook
            - name: TOOLS_TAG
              value: "prod"
            resources:
              requests:
                memory: 11Gi
                cpu: 3000m
              limits:
                memory: 11Gi
                cpu: 6000m
          imagePullSecrets:
            - name: hsldevcomkey
---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-finland-prod-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-finland-prod
