---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-data-builder-finland-dev
spec:
  schedule: "30 17 * * *" # schedule in Finland time
  timeZone: "Europe/Helsinki"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-data-builder-finland-dev
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 9000 # one build can take max 2 hours and 30 minutes
          restartPolicy: OnFailure
          nodeSelector:
            pool: megapool
          containers:
          - name: otp-data-builder-finland-dev
            image: hsldevcom/otp-data-builder:latest
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: BUILDER_TYPE
              value: "Finland dev"
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: DOCKER_TAG
              value: "latest"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: SLACK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-access-token
                  key: slack-access-token
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slack-ci-channel-id
                  key: slack-ci-channel-id
            - name: OTP_TAG
              value: "latest"
            - name: ROUTERS
              value: "finland"
            - name: SEED_TAG
              value: "latest"
            - name: TOOLS_TAG
              value: "latest"
            - name: SKIPPED_SITES
              value: "reittiopas.hsl.fi"
            resources:
              requests:
                memory: 11Gi
                cpu: 3000m
              limits:
                memory: 11Gi
                cpu: 6000m
          imagePullSecrets:
            - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-finland-dev-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-finland-dev
