---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-data-builder-waltti-dev-v3
spec:
  schedule: "50 23 * * *" # schedule in Finland time
  timeZone: "Europe/Helsinki"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-data-builder-waltti-dev-v3
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 9000 # one build can take max 2 hours and 30 minutes
          restartPolicy: OnFailure
          nodeSelector:
            agentpool: userpooltest
          tolerations:
          - key: "testingPod"
            operator: "Equal"
            value: "yes"
            effect: "NoSchedule"
          containers:
          - name: otp-data-builder-waltti-dev-v3
            image: hsldevcom/otp-data-builder:v3
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: ROUTER_NAME
              value: "waltti"
            - name: BUILDER_TYPE
              value: "Waltti dev v3"
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: EXTRA_SRC
              value: "{\"Lahti\": {\"url\": \"https://www.lsl.fi/tiedostot/testidata\", \"request\": {\"insecureHTTPParser\": true}}, \"Kuopio\": {\"url\": \"https://kartta.kuopio.fi/google_transit/testi.zip\"}}"
            - name: EXTRA_UPDATERS
              value: "{\"tampere-alerts\": {\"url\": \"http://digitransit-proxy:8080/out/lmj.mattersoft.fi/api/gtfsrealtime/v1.0/feed/servicealert\"}, \"tampere-trip-updates\": {\"url\": \"https://gtfsrt.blob.core.windows.net/lmj/tripupdate\"}}"
            - name: SKIPPED_SITES
              value: "kuopio.digitransit.fi"
            - name: DOCKER_TAG
              value: "v3"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: SLACK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-access-token
                  key: slack-access-token
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slack-ci-channel-id
                  key: slack-ci-channel-id
            - name: OTP_TAG
              value: "v2"
            - name: SEED_TAG
              value: "v3"
            - name: TOOLS_TAG
              value: "v3"
            - name: SLACK_CHANNEL
              value: "topic-ci-otp2"
            resources:
              requests:
                memory: 11Gi
                cpu: 3000m
              limits:
                memory: 11Gi
                cpu: 4000m
          imagePullSecrets:
            - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-waltti-dev-v3-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-waltti-dev-v3
