---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pelias-data-container-builder-prod
spec:
  schedule: "40 3 * * *"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: pelias-data-container-builder-prod
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 7200 # one build can take max 2 hours
          restartPolicy: OnFailure
          nodeSelector:
            pool: megapool
          containers:
          - name: pelias-data-container-builder-prod
            image: hsldevcom/pelias-data-container-builder:prod
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: API_SUBSCRIPTION_QUERY_PARAMETER_NAME
              valueFrom:
                secretKeyRef:
                  name: "digitransit-subscription-key-name"
                  key: "digitransit-subscription-key-name"
            - name: API_SUBSCRIPTION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "prod-pelias-data-container-builder-apim-key"
                  key: "prod-pelias-data-container-builder-apim-key"
            - name: GTFS_AUTH
              valueFrom:
                secretKeyRef:
                  name: next-waltti-basic
                  key: next-waltti-basic
            - name: BUILDER_TYPE
              value: "prod"
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook
                  key: slack-webhook
            - name: MMLAPIKEY
              valueFrom:
                secretKeyRef:
                  name: mmlapikey
                  key: mmlapikey
            - name: BUILD_INTERVAL
              value: "-1" # builder shuts down after first build
            - name: SLACK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-access-token
                  key: slack-access-token
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slack-ci-channel-id
                  key: slack-ci-channel-id
            resources:
              requests:
                memory: 8Gi
                cpu: 2000m
              limits:
                memory: 8Gi
                cpu: 4000m
          imagePullSecrets:
            - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pelias-data-container-builder-prod-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pelias-data-container-builder-prod
