---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pelias-data-container-builder-dev
spec:
  schedule: "32 10 * * *"
  timeZone: "Europe/Helsinki"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: pelias-data-container-builder-dev
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 9000 # one build can take 2 and half hours
          restartPolicy: OnFailure
          nodeSelector:
            agentpool: builderpool
          tolerations:
          - key: "builder"
            operator: "Equal"
            value: "yes"
            effect: "NoSchedule"
          containers:
          - name: pelias-data-container-builder-dev
            image: hsldevcom/pelias-data-container-builder
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: API_SUBSCRIPTION_QUERY_PARAMETER_NAME
              valueFrom:
                secretKeyRef:
                  name: "digitransit-subscription-key-name"
                  key: "digitransit-subscription-key-name"
            - name: API_SUBSCRIPTION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "dev-pelias-data-container-builder-apim-key"
                  key: "dev-pelias-data-container-builder-apim-key"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: GTFS_AUTH
              valueFrom:
                secretKeyRef:
                  name: next-waltti-basic
                  key: next-waltti-basic
            - name: BUILDER_TYPE
              value: "dev"
            - name: MMLAPIKEY
              valueFrom:
                secretKeyRef:
                  name: mmlapikey
                  key: mmlapikey
            - name: BUILD_INTERVAL
              value: "-1" # builder shuts down after first build
            - name: THRESHOLD
              value: "5"
            - name: SLACK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-access-token
                  key: slack-access-token
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slack-ci-channel-id
                  key: slack-ci-channel-id
            resources:
              requests:
                memory: 9Gi
                cpu: 7000m
              limits:
                memory: 9Gi
                cpu: 8000m
          imagePullSecrets:
            - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pelias-data-container-builder-dev-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pelias-data-container-builder-dev
