---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pelias-data-container-builder
spec:
  schedule: "30 0 * * *" # schedule in UTC time
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 18000 # build(s) can take max 5 hours in total
          restartPolicy: OnFailure
          containers:
          - name: pelias-data-container-builder
            image: hsldevcom/pelias-data-container-builder
            volumeMounts:
              - mountPath: var/run/docker.sock
                name: "docker-sock-volume"
            imagePullPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
            env:
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: DOCKER_API_VERSION #TODO this should be removed from code and it should use default
              value: "1.38"
            - name: DOCKER_TAG
              value: "latest"
            - name: BUILDER_TYPE
              value: "prod"
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook
                  key: slack-webhook
            - name: MMLAPIKEY
              valueFrom:
                secretKeyRef:
                  name: mmlapikey
                  key: mmlapikey
            - name: BUILD_INTERVAL
              value: "-1" # builder shuts down after first build
            resources:
              requests:
                memory: 6Gi
                cpu: 2000m
              limits:
                memory: 6Gi
                cpu: 7000m
          volumes:
            - name: "docker-sock-volume"
              hostPath:
                # location on host
                path: /var/run/docker.sock
