apiVersion: v1
kind: Service
metadata:
  name: redis-hsl
spec:
  selector:
    app: redis-hsl
  ports:
  - port: 8080
    targetPort: 6379
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-hsl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-hsl
  template:
    metadata:
      labels:
        app: redis-hsl
    spec:
      containers:
      - name: redis-hsl
        image: redis
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080

