apiVersion: v1
kind: Service
metadata:
  name: siri2gtfsrt
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: siri2gtfsrt-service-port
    protocol: TCP
  selector:
    app: siri2gtfsrt
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: siri2gtfsrt
  labels:
    app: siri2gtfsrt
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: siri2gtfsrt
  template:
    metadata:
      labels:
        app: siri2gtfsrt
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      containers:
      - name: siri2gtfsrt
        image: hsldevcom/siri2gtfsrt
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: /FOLI
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: /FOLI
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"      
