---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "keyvault-yleisviestipalvelu"
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "8274e895-09f9-424f-afa1-9ed7c6fc23e6"
    tenantId: "572a41dd-c389-4f0a-b256-aefd1bf149d7"
    keyvaultName: "digitransit-dev-keyvault"
    objects: |
      array:
        - |
          objectName: ht-password
          objectType: secret
  secretObjects:
    - secretName: "kv-ht-password"
      type: Opaque
      data:
        - objectName: ht-password
          key: ht-password
---
apiVersion: v1
kind: Service
metadata:
  name: yleisviestipalvelu
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: yleisviestipalvelu-service-port
  selector:
    app: yleisviestipalvelu
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yleisviestipalvelu
  labels:
    app: yleisviestipalvelu
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: yleisviestipalvelu
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: yleisviestipalvelu
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - yleisviestipalvelu
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        agentpool: burstpool
      serviceAccountName: keyvault-secrets
      containers:
      - name: yleisviestipalvelu
        image: hsldevcom/yleisviestipalvelu
        volumeMounts:
          - name: keyvault
            mountPath: /mnt/keyvault
            readOnly: true
          - mountPath: /yleisviestipalvelu/messages
            name: yleisviestipalvelumessages
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: /
        livenessProbe:
          initialDelaySeconds: 12
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: /
        env:
        - name: HTPASSWD
          valueFrom:
            secretKeyRef:
              name: kv-ht-password
              key: ht-password
        resources:
          requests:
            memory: "30Mi"
            cpu: "20m"
          limits:
            memory: "50Mi"
            cpu: "50m"
      imagePullSecrets:
        - name: kv-hsldevcomkey
      volumes:
        - name: keyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: keyvault-yleisviestipalvelu
        - name: "yleisviestipalvelumessages"
          persistentVolumeClaim:
            claimName: yleisviesti-fileshare
