apiVersion: v1
kind: Service
metadata:
  name: yleisviestipalvelu
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: yleisviestipalvelu-service-port
  selector:
    app: yleisviestipalvelu
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: yleisviestipalvelu
  labels:
    app: yleisviestipalvelu
    update: auto
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: yleisviestipalvelu
  template:
    metadata:
      labels:
        app: yleisviestipalvelu
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - yleisviestipalvelu
              topologyKey: kubernetes.io/hostname
      priorityClassName: medium-priority
      nodeSelector:
        pool: defaultpool
      containers:
      - name: yleisviestipalvelu
        image: hsldevcom/yleisviestipalvelu:prod
        volumeMounts:
          - mountPath: /yleisviestipalvelu/messages
            name: yleisviestipalvelumessages
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: /
        livenessProbe:
          initialDelaySeconds: 12
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: /
        env:
        - name: HTPASSWD
          valueFrom:
            secretKeyRef:
              name: ht-password
              key: ht-password
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"
      imagePullSecrets:
        - name: hsldevcomkey
      volumes:
        - name: "yleisviestipalvelumessages"
          persistentVolumeClaim:
            claimName: yleisviesti-fileshare
