apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-matka-v3
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-matka-v3-service-port
  selector:
    app: digitransit-ui-matka-v3
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-matka-v3
  labels:
    app: digitransit-ui-matka-v3
    update: auto
    restartAt: "05.50_15.50"
    restartLimitInterval: "480"
    restartAfterDeployments: "opentripplanner-finland-v2"
    restartDelay: "5"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-matka-v3
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: digitransit-ui-matka-v3
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-ui-matka-v3
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        agentpool: burstpool
      containers:
      - name: digitransit-ui-matka-v3
        image: hsldevcom/digitransit-ui:v3-prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: API_URL
          value: "https://api.digitransit.fi"
        - name: FAVOURITE_HOST
          value: "https://api.digitransit.fi/favourites"
        - name: ASSET_URL
          value: "https://cdn.digitransit.fi/ui/v3/matka"
        - name: MAP_URL
          value: "https://cdn.digitransit.fi"
        - name: NODE_OPTS
          value: "--max_old_space_size=1500"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: STATIC_MESSAGE_URL
          value: "https://matka-yleisviesti.digitransit.fi"
        - name: API_SUBSCRIPTION_QUERY_PARAMETER_NAME
          valueFrom:
            secretKeyRef:
              name: "digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_HEADER_NAME
          valueFrom:
            secretKeyRef:
              name: "digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: "digitransit-ui-matka-v3-apim-key"
              key: "digitransit-ui-matka-v3-apim-key"
        - name: ASSEMBLE_GEOJSON
          value: "1"
        - name: CITYBIKE_DB_CONN_STRING
          valueFrom:
            secretKeyRef:
              name: prod-citybike-scheduler-db-conn-string
              key: prod-citybike-scheduler-db-conn-string
        - name: CITYBIKE_DATABASE
          value: "citybike-scheduler-prod"
        - name: MAP_VERSION
          value: "v3"
        resources:
          requests:
            memory: 2Gi
            cpu: 600m
          limits:
            memory: 2Gi
            cpu: 1500m
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: digitransit-ui-matka-v3-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: digitransit-ui-matka-v3

