apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-matka
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-matka-service-port
  selector:
    app: digitransit-ui-matka-v2
---
apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-default
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-default-service-port
  selector:
    app: digitransit-ui-matka-v2
