apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-waltti
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-waltti-service-port
  selector:
    app: digitransit-ui-waltti-v2
