apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-apim-test
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-apim-test-service-port
  selector:
    app: digitransit-ui-apim-test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-apim-test
  labels:
    app: digitransit-ui-apim-test
    update: auto
spec:
  selector:
    matchLabels:
      app: digitransit-ui-apim-test
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: digitransit-ui-apim-test
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-ui-apim-test
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: defaultpool
      containers:
      - name: digitransit-ui-apim-test
        image: hsldevcom/digitransit-ui:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /etusivu
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /etusivu
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: CONFIG
          value: "tampere"
        - name: API_URL
          value: "https://dev-next-api.digitransit.fi"
        - name: ASSET_URL
          value: "https://dev-next-api.digitransit.fi/ui/v2/waltti"
        - name: MAP_URL
          value: "https://dev-next-api.digitransit.fi"
        - name: NODE_OPTS
          value: "--max_old_space_size=1000"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        resources:
          requests:
            memory: "1536Mi"
            cpu: 600m
          limits:
            memory: "1536Mi"
            cpu: 2000m
      imagePullSecrets:
        - name: hsldevcomkey
