apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-matka
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-matka-service-port
  selector:
    app: digitransit-ui-matka
---
apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-default
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-default-service-port
  selector:
    app: digitransit-ui-matka
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-matka
  labels:
    app: digitransit-ui-matka
    update: auto
    restartAt: "03.00_13.00"
    restartLimitInterval: "480"
    restartAfterDeployments: "opentripplanner-finland"
    restartDelay: "5"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-matka
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: digitransit-ui-matka
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-ui-matka
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: defaultpool
      containers:
      - name: digitransit-ui-matka
        image: hsldevcom/digitransit-ui:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: CONFIG
          value: "matka"
        - name: API_URL
          value: "https://api.digitransit.fi"
        - name: ASSET_URL
          value: "https://digitransit-prod-cdn-origin.azureedge.net/ui/v1/finland"
        - name: MAP_URL
          value: "https://digitransit-prod-cdn-origin.azureedge.net"
        - name: NODE_OPTS
          value: "--max_old_space_size=600"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry-dsn
              key: sentry-dsn
        #- name: SENTRY_SECRET_DSN
        #  valueFrom:
        #    secretKeyRef:
        #      name: sentry-secret-dsn
        #      key: sentry-secret-dsn
        resources:
          requests:
            memory: 1024Mi
            cpu: 500m
          limits:
            memory: 1024Mi
            cpu: 2000m
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: digitransit-ui-matka-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: digitransit-ui-matka
