apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-hsl-v3
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-hsl-v3-service-port
  selector:
    app: digitransit-ui-hsl-v3
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-hsl-v3
  labels:
    app: digitransit-ui-hsl-v3
    update: auto
    restartAt: "05.10_15.10"
    restartLimitInterval: "480"
    restartAfterDeployments: "opentripplanner-hsl-v2_hsl-timetable-container"
    restartDelay: "5"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-hsl-v3
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: digitransit-ui-hsl-v3
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-ui-hsl-v3
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        agentpool: burstpool
      containers:
      - name: digitransit-ui-hsl-v3
        image: hsldevcom/digitransit-ui:v3-prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        startupProbe:
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 20
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 2
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
        env:
        - name: CONFIG
          value: "hsl"
        - name: HOSTNAME
          value: "https://reittiopas.hsl.fi"
        - name: API_URL
          value: "https://api.digitransit.fi"
        - name: FAVOURITE_HOST
          value: "https://api.digitransit.fi/favourites"
        - name: ASSET_URL
          value: "https://cdn.digitransit.fi/ui/v3/hsl"
        - name: ROOTLINK
          value: "https://www.hsl.fi"
        - name: MAP_URL
          value: "https://cdn.digitransit.fi"
        - name: NODE_OPTS
          value: "--max_old_space_size=1500"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: API_SUBSCRIPTION_QUERY_PARAMETER_NAME
          valueFrom:
            secretKeyRef:
              name: "digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_HEADER_NAME
          valueFrom:
            secretKeyRef:
              name: "digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: "digitransit-ui-hsl-v3-apim-key"
              key: "digitransit-ui-hsl-v3-apim-key"
        - name: GTM_ID
          valueFrom:
            secretKeyRef:
              name: gtm-id
              key: gtm-id
        - name: USE_EMITTER
          value: "1"
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: redis-host
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_KEY
          valueFrom:
            secretKeyRef:
              name: redis-key
              key: redis-key
        - name: OIDCHOST
          value: "https://id.hsl.fi"
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: session-secret
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: prod-oidc-client-id
              key: prod-oidc-client-id
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: prod-oidc-client-secret
              key: prod-oidc-client-secret
        - name: NOTIFICATION_HOST
          value: "https://www.hsl.fi/user/api/v1/notifications"
        - name: STOP_TIMETABLES_URL
          value: "https://kartat.hsl.fi"
        - name: BANNER_URL
          value: "https://content.hsl.fi/api/v1/banners?site=JourneyPlanner"
        - name: CONTENT_DOMAIN
          value: "https://cms.hsl.fi"
        - name: CITYBIKE_DB_CONN_STRING
          valueFrom:
            secretKeyRef:
              name: prod-citybike-scheduler-db-conn-string
              key: prod-citybike-scheduler-db-conn-string
        - name: CITYBIKE_DATABASE
          value: "citybike-scheduler-prod"
        - name: MAP_VERSION
          value: "v3"
        resources:
          requests:
            memory: 3Gi
            cpu: 800m
          limits:
            memory: 3Gi
            cpu: 1000m
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: digitransit-ui-hsl-v3-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: digitransit-ui-hsl-v3
