apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-hsl-v3
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-hsl-v3-service-port
  selector:
    app: digitransit-ui-hsl-v3
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-hsl-v3
  labels:
    app: digitransit-ui-hsl-v3
    update: auto
    restartAt: "05.10_15.10"
    restartLimitInterval: "480"
    restartAfterDeployments: "opentripplanner-hsl-v2"
    restartDelay: "5"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-hsl-v3
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: digitransit-ui-hsl-v3
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-ui-hsl-v3
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: smallpool
      containers:
      - name: digitransit-ui-hsl-v3
        image: hsldevcom/digitransit-ui:v3-prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: CONFIG
          value: "hsl"
        - name: HOSTNAME
          value: "https://reittiopas.hsl.fi"
        - name: API_URL
          value: "https://api.digitransit.fi"
        - name: FAVOURITE_HOST
          value: "https://api.digitransit.fi/favourites"
        - name: ASSET_URL
          value: "https://digitransit-prod-cdn-origin.azureedge.net/ui/v3/hsl"
        - name: ROOTLINK
          value: "https://www.hsl.fi"
        - name: MAP_URL
          value: "https://digitransit-prod-cdn-origin.azureedge.net"
        - name: NODE_OPTS
          value: "--max_old_space_size=1500"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        # - name: SENTRY_DSN
        #   valueFrom:
        #     secretKeyRef:
        #       name: sentry-dsn
        #       key: sentry-dsn
        - name: API_SUBSCRIPTION_QUERY_PARAMETER_NAME
          valueFrom:
            secretKeyRef:
              name: "digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_HEADER_NAME
          valueFrom:
            secretKeyRef:
              name: "digitransit-subscription-key-name"
              key: "digitransit-subscription-key-name"
        - name: API_SUBSCRIPTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: "digitransit-ui-hsl-v3-apim-key"
              key: "digitransit-ui-hsl-v3-apim-key"
        # - name: SENTRY_SECRET_DSN
        #   valueFrom:
        #     secretKeyRef:
        #       name: sentry-secret-dsn
        #       key: sentry-secret-dsn
        #- name: GTM_ID
        #  valueFrom:
        #    secretKeyRef:
        #      name: gtm-id
        #      key: gtm-id
        - name: DISABLEBATCHQUERIES
          value: "1"
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-host
              key: redis-host
        - name: REDIS_PORT
          value: "6380"
        - name: REDIS_KEY
          valueFrom:
            secretKeyRef:
              name: redis-key
              key: redis-key
        - name: OIDCHOST
          value: "https://id.hsl.fi"
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: session-secret
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: prod-oidc-client-id
              key: prod-oidc-client-id
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: prod-oidc-client-secret
              key: prod-oidc-client-secret
        - name: NOTIFICATION_HOST
          value: "https://www.hsl.fi/user/api/v1/notifications"
        resources:
          requests:
            memory: 2Gi
            cpu: 600m
          limits:
            memory: 2Gi
            cpu: 1500m
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: digitransit-ui-hsl-v3-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: digitransit-ui-hsl-v3
