apiVersion: v1
kind: Service
metadata:
  name: digitransit-proxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: digitransit-proxy-service-port-1
  - port: 8080
    targetPort: 8080
    name: digitransit-proxy-service-port-2
  selector:
    app: digitransit-proxy
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-proxy
  labels:
    app: digitransit-proxy
    update: auto
spec:
  selector:
    matchLabels:
      app: digitransit-proxy
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: digitransit-proxy
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-proxy
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        agentpool: burstpool
      containers:
      - name: digitransit-proxy
        image: hsldevcom/digitransit-proxy:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: /
        livenessProbe:
          initialDelaySeconds: 150
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: /
        env:
          - name: NEW_HSL_FI_URL
            value: "www.hsl.fi"
          - name: JOJO_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: jojo-basic-key
                key: jojo-basic-key
          - name: LINKKI_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: linkki-basic-key
                key: linkki-basic-key
          - name: VILKKU_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: vilkku-basic-key
                key: vilkku-basic-key
          - name: NEW_LISSU_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: new-lissu-basic-key
                key: new-lissu-basic-key
          - name: LAPPEENRANTA_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: lappeenranta-basic-key
                key: lappeenranta-basic-key
          - name: LAHTI_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: lahti-basic-key
                key: lahti-basic-key
          - name: HAMEENLINNA_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: hameenlinna-basic-key
                key: hameenlinna-basic-key
          - name: LMJ_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: lmj-basic-key
                key: lmj-basic-key
          - name: MIKKELI_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: mikkeli-basic-key
                key: mikkeli-basic-key
          - name: VAASA_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: vaasa-basic-key
                key: vaasa-basic-key
          - name: VARELY_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: varely-basic-key
                key: varely-basic-key
          - name: SALO_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: salo-basic-key
                key: salo-basic-key
          - name: KOUVOLA_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: kouvola-basic-key
                key: kouvola-basic-key
          - name: GIRAVOLTA_TAMPERE_AUTH
            valueFrom:
              secretKeyRef:
                name: giravolta-tampere-key
                key: giravolta-tampere-key
          - name: KOTKA_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: kotka-basic-key
                key: kotka-basic-key
          - name: ROVANIEMI_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: rovaniemi-basic-key
                key: rovaniemi-basic-key
          - name: KAJAANI_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: kajaani-basic-key
                key: kajaani-basic-key
          - name: GIRAVOLTA_VANTAA_AUTH
            valueFrom:
              secretKeyRef:
                name: giravolta-vantaa-key
                key: giravolta-vantaa-key
          - name: RAUMA_RT_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: rauma-rt-basic-key
                key: rauma-rt-basic-key
          - name: OULU_RT_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: oulu-rt-basic-key
                key: oulu-rt-basic-key
          - name: PORI_RT_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: pori-rt-basic-key
                key: pori-rt-basic-key
          - name: RAUMA_STATIC_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: rauma-static-basic-key
                key: rauma-static-basic-key
          - name: MH_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: mh-basic-key
                key: mh-basic-key
          - name: RAASEPORI_RT_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: raasepori-rt-basic-key
                key: raasepori-rt-basic-key
          - name: VARELY_RT_BASIC_AUTH
            valueFrom:
              secretKeyRef:
                name: varely-rt-basic-key
                key: varely-rt-basic-key
          - name: CDN_BASE_URL
            value: "https://cdn.digitransit.fi"
        resources:
            requests:
              memory: "1152Mi"
              cpu: "1000m"
            limits:
              memory: "1152Mi"
              cpu: "1500m"
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: digitransit-proxy-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: digitransit-proxy
