apiVersion: v1
kind: Service
metadata:
  name: digitransit-ui-linjasto2021
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: digitransit-ui-linjasto2021-service-port
  selector:
    app: digitransit-ui-linjasto2021
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitransit-ui-linjasto2021
  labels:
    app: digitransit-ui-linjasto2021
    update: auto
    restartAt: "03.10_13.10"
    restartLimitInterval: "480"
    restartAfterDeployments: "opentripplanner-linjasto2021-waltti"
    restartDelay: "5"
spec:
  selector:
    matchLabels:
      app: digitransit-ui-linjasto2021
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: digitransit-ui-linjasto2021
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - digitransit-ui-linjasto2021
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: defaultpool
      containers:
      - name: digitransit-ui-linjasto2021
        image: hsldevcom/digitransit-ui:ratikka
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        env:
        - name: API_URL
          value: "https://api.digitransit.fi"
        - name: ASSET_URL
          value: "https://digitransit-prod-cdn-origin.azureedge.net/ui/v1/linjasto2021"
        - name: MAP_URL
          value: "https://digitransit-prod-cdn-origin.azureedge.net"
        - name: NODE_OPTS
          value: "--max_old_space_size=900"
        - name: RELAY_FETCH_TIMEOUT
          value: "3000"
        - name: GTM_ID
          valueFrom:
            secretKeyRef:
              name: gtm-id
              key: gtm-id
        - name: BASE_CONFIG
          value: "waltti"
        resources:
          requests:
            memory: 1200Mi
            cpu: 500m
          limits:
            memory: 1200Mi
            cpu: 2000m
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: digitransit-ui-linjasto2021-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: digitransit-ui-linjasto2021
