apiVersion: v1
kind: Service
metadata:
  name: hsl-map-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: hsl-map-server-service-port
    protocol: TCP
  selector:
    app: hsl-map-server
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsl-map-server
  labels:
    app: hsl-map-server
    update: auto
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hsl-map-server
  template:
    metadata:
      labels:
        app: hsl-map-server
        lastRestartDate: dummy-value
    spec:
      nodeSelector:
        agentpool: powerpool
      tolerations:
      - key: "powerPod"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      containers:
      - name: hsl-map-server
        image: hsldevcom/hsl-map-server:prod
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: /map/v2/hsl-map/index.json
        livenessProbe:
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
          httpGet:
            port: 8080
            path: /map/v2/hsl-map/index.json
        env:
          # TODO update these envs to use otp2
          - name: FINLAND_OTP_URL
            value: "opentripplanner-finland:8080/otp/routers/finland/index/graphql"
          - name: HSL_OTP_URL
            value: "opentripplanner-hsl:8080/otp/routers/hsl/index/graphql"
          - name: NODE_OPTS
            value: "--max_old_space_size=2048 --optimize_for_size --stack_size=2048 --harmony"
          - name: WALTTI_OTP_URL
            value: "opentripplanner-waltti:8080/otp/routers/waltti/index/graphql"
          - name: PARKANDRIDE_URL
            value: "https://parking.fintraffic.fi/api/v1/"
        resources:
          requests:
            memory: 10Gi
            cpu: 3000m
          limits:
            memory: 10Gi
            cpu: 4000m
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hsl-map-server-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: hsl-map-server
