apiVersion: v1
kind: Service
metadata:
  name: hsl-timetable-container
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: hsl-timetable-container-service-port
    protocol: TCP
  selector:
    app: hsl-timetable-container
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsl-timetable-container
  labels:
    app: hsl-timetable-container
    update: auto
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: hsl-timetable-container
  template:
    metadata:
      labels:
        app: hsl-timetable-container
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: Exists
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: superpool
      containers:
      - name: hsl-timetable-container
        image: hsldevcom/hsl-timetable-container
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/version.txt"
        livenessProbe:
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/version.txt"
        resources:
          requests:
            memory: "48Mi"
            cpu: "100m"
          limits:
            memory: "48Mi"
            cpu: "100m"
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: hsl-timetable-container-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: hsl-timetable-container
