apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-data-server-finland
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-data-server-finland-service-port
    protocol: TCP
  selector:
    app: opentripplanner-data-server-finland
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-data-server-finland
  labels:
    app: opentripplanner-data-server-finland
    update: auto
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: opentripplanner-data-server-finland
  template:
    metadata:
      labels:
        app: opentripplanner-data-server-finland
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - opentripplanner-data-server-finland
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        agentpool: burstpool
      containers:
      - name: opentripplanner-data-server-finland
        image: hsldevcom/opentripplanner-data-server:v2-prod-finland
        volumeMounts:
          - mountPath: /var/www/localhost/htdocs
            name: datastorage
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/version.txt"
        livenessProbe:
          initialDelaySeconds: 500
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/version.txt"
        resources:
          requests:
            memory: "224Mi"
            cpu: "100m"
          limits:
            memory: "224Mi"
            cpu: "200m"
      imagePullSecrets:
        - name: hsldevcomkey
      volumes:
        - name: "datastorage"
          persistentVolumeClaim:
            claimName: otp-data-finland-v2-pvc
            readOnly: true

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opentripplanner-data-server-finland-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: opentripplanner-data-server-finland
