apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-data-server-hsl
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-data-server-hsl-service-port
    protocol: TCP
