apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-waltti
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-waltti-service-port
  selector:
    app: opentripplanner-waltti

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-waltti
  labels:
    app: opentripplanner-waltti
    update: auto
    restartDelay: "5"
    restartAt: "05.45"
    restartLimitInterval: "720"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: opentripplanner-waltti
  template:
    metadata:
      labels:
        app: opentripplanner-waltti
        lastRestartDate: dummy-value
    spec:
      nodeSelector:
        agentpool: powerpool
      tolerations:
      - key: "powerPod"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      containers:
      - name: opentripplanner-waltti
        image: hsldevcom/opentripplanner:v1-prod-waltti
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: datastorage
            mountPath: /var/otp/
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/routers/waltti/"
        startupProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 380 # leave enough time for potential graph build
          httpGet:
            port: 8080
            path: "/otp/routers/waltti/"
        livenessProbe:
          periodSeconds: 120
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/otp/routers/waltti/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: JAVA_OPTS
          value: "-Xmx10G -Xms10G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1ReservePercent=10  -XX:+PrintGC"
        resources:
          requests:
            memory: 11Gi
            cpu: "3000m"
          limits:
            memory: 11Gi
            cpu: "4000m"
      imagePullSecrets:
        - name: hsldevcomkey
      volumes:
      - name: "datastorage"
        persistentVolumeClaim:
          claimName: otp-data-waltti-v2-pvc
          readOnly: true

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opentripplanner-waltti-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: opentripplanner-waltti
