apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-finland
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-finland-service-port
  selector:
    app: opentripplanner-finland

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-finland
  labels:
    app: opentripplanner-finland
    restartAfterDeployments: "opentripplanner-data-con-finland"
    restartDelay: "5"
    restartAt: "05.30"
    restartLimitInterval: "720"
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: opentripplanner-finland
  template:
    metadata:
      labels:
        app: opentripplanner-finland
        lastRestartDate: dummy-value
    spec:
      nodeSelector:
        pool: megapool
      containers:
      - name: opentripplanner-finland
        image: hsldevcom/opentripplanner:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 15
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/routers/finland/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ROUTER_DATA_CONTAINER_URL
          value: "http://opentripplanner-data-con-finland:8080"
        - name: ROUTER_NAME
          value: "finland"
        - name: JAVA_OPTS
          value: "-Xmx18G -Xms18G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1ReservePercent=10 -XX:+PrintGC"
        resources:
          requests:
            memory: 20Gi
            cpu: "7000m"
          limits:
            memory: 20Gi
            cpu: "8000m"
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opentripplanner-finland-pdb
spec:
  minAvailable: 75%
  selector:
    matchLabels:
      app: opentripplanner-finland
