apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-data-con-waltti
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-data-con-waltti-service-port
    protocol: TCP
  selector:
    app: opentripplanner-data-con-waltti
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-data-con-waltti
  labels:
    app: opentripplanner-data-con-waltti
    update: auto
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: opentripplanner-data-con-waltti
  template:
    metadata:
      labels:
        app: opentripplanner-data-con-waltti
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - opentripplanner-data-con-waltti
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: defaultpool
      containers:
      - name: opentripplanner-data-con-waltti
        image: hsldevcom/opentripplanner-data-container-waltti:prod
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/version.txt"
        livenessProbe:
          initialDelaySeconds: 500
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 25
          httpGet:
            port: 8080
            path: "/version.txt"
        resources:
          requests:
            memory: "224Mi"
            cpu: "100m"
          limits:
            memory: "224Mi"
            cpu: "200m"
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: opentripplanner-data-con-waltti-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: opentripplanner-data-con-waltti
