apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-finland
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-finland-service-port
  selector:
    app: opentripplanner-finland

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-finland
  labels:
    app: opentripplanner-finland
    update: auto
    restartDelay: "5"
    restartAt: "05.30"
    restartLimitInterval: "720"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: opentripplanner-finland
  template:
    metadata:
      labels:
        app: opentripplanner-finland
    spec:
      nodeSelector:
        agentpool: powerpool
      tolerations:
      - key: "powerPod"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      containers:
      - name: opentripplanner-finland
        image: hsldevcom/opentripplanner:v1-prod-finland
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: datastorage
            mountPath: /var/otp/
        startupProbe:
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 80
          httpGet:
            port: 8080
            path: "/otp/routers/finland/"
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
          httpGet:
            port: 8080
            path: "/otp/routers/finland/"
        livenessProbe:
          periodSeconds: 12
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/otp/routers/finland/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: JAVA_OPTS
          value: "-Xmx10G -Xms10G -XX:+UseParNewGC -XX:NewRatio=5 -XX:+UseStringDeduplication -XX:+PrintGC"
        resources:
          requests:
            memory: 11Gi
            cpu: "3000m"
          limits:
            memory: 11Gi
            cpu: "4000m"
      imagePullSecrets:
        - name: hsldevcomkey
      volumes:
      - name: "datastorage"
        nfs:
            server: digitransitprdaksstorage.file.core.windows.net
            path: /digitransitprdaksstorage/finland
            readOnly: true

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opentripplanner-finland-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: opentripplanner-finland
