apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-waltti-alt-v2
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-waltti-alt-v2-service-port
  selector:
    app: opentripplanner-waltti-alt-v2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-waltti-alt-v2
  labels:
    app: opentripplanner-waltti-alt-v2
    update: auto
    restartDelay: "1"
    restartAt: "05.45"
    restartLimitInterval: "720"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: opentripplanner-waltti-alt-v2
  template:
    metadata:
      labels:
        app: opentripplanner-waltti-alt-v2
        lastRestartDate: dummy-value
    spec:
      nodeSelector:
        agentpool: powerpool
      tolerations:
      - key: "powerPod"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      containers:
      - name: opentripplanner-waltti-alt-v2
        image: hsldevcom/opentripplanner:v2-prod-waltti-alt
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: otpcfgmap
            mountPath: /opt/opentripplanner/logback-include-extensions.xml
            subPath: file-from-cfgmap
          - name: datastorage
            mountPath: /var/otp/
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/routers/default/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: JAVA_OPTS
          value: "-Xmx8728m -Xms8728m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1ReservePercent=10  -Xlog:gc"
        resources:
          requests:
            memory: "10Gi"
            cpu: "3000m"
          limits:
            memory: "10Gi"
            cpu: "4000m"
      volumes:
      - name: otpcfgmap
        configMap:
          name: opentripplanner-cfgmap
      - name: "datastorage"
        persistentVolumeClaim:
          claimName: otp-data-waltti-alt-v3-pvc
          readOnly: true
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opentripplanner-waltti-alt-v2-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: opentripplanner-waltti-alt-v2
