apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-waltti-alt-v2
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-waltti-alt-v2-service-port
  selector:
    app: opentripplanner-waltti-alt-v2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-waltti-alt-v2
  labels:
    app: opentripplanner-waltti-alt-v2
    restartAfterDeployments: "opentripplanner-data-con-waltti-alt-v3"
    restartDelay: "1"
    restartAt: "05.45"
    restartLimitInterval: "720"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: opentripplanner-waltti-alt-v2
  template:
    metadata:
      labels:
        app: opentripplanner-waltti-alt-v2
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - opentripplanner-waltti-alt-v2
		  - opentripplanner-kela-v2
		  - hsl-map-server
                  - pelias-api
                  - pelias-data-container
              topologyKey: kubernetes.io/hostname
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - opentripplanner-varely-v2
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: megapool
      containers:
      - name: opentripplanner-waltti-alt-v2
        image: hsldevcom/opentripplanner:v2-prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: otpcfgmap
            mountPath: /opt/opentripplanner/logback-include-extensions.xml
            subPath: file-from-cfgmap
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/routers/default/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ROUTER_DATA_CONTAINER_URL
          value: "http://opentripplanner-data-con-waltti-alt-v3:8080"
        - name: ROUTER_NAME
          value: "waltti-alt"
        - name: JAVA_OPTS
          value: "-Xmx9728m -Xms9728m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1ReservePercent=10  -Xlog:gc"
        resources:
          requests:
            memory: "11Gi"
            cpu: "3000m"
          limits:
            memory: "11Gi"
            cpu: "7000m"
      volumes:
      - name: otpcfgmap
        configMap:
          name: opentripplanner-cfgmap
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opentripplanner-waltti-alt-v2-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: opentripplanner-waltti-alt-v2
