apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opentripplanner-kela-v2-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opentripplanner-kela-v2
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 100
        periodSeconds: 600
    scaleDown:
      stabilizationWindowSeconds: 600 # 5 min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 600

