apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-hsl
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-hsl-service-port
  selector:
    app: opentripplanner-hsl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentripplanner-hsl
  labels:
    app: opentripplanner-hsl
    restartAfterDeployments: "opentripplanner-data-con-hsl"
    restartDelay: "5"
    restartAt: "05.15"
    restartLimitInterval: "720"
spec:
  replicas: 32
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: opentripplanner-hsl
  template:
    metadata:
      labels:
        app: opentripplanner-hsl
        lastRestartDate: dummy-value
    spec:
      nodeSelector:
        pool: superpool
      containers:
      - name: opentripplanner-hsl
        image: hsldevcom/opentripplanner:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 2
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/otp/routers/hsl/"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ROUTER_DATA_CONTAINER_URL
          value: "http://opentripplanner-data-con-hsl:8080"
        - name: ROUTER_NAME
          value: "hsl"
        - name: JAVA_OPTS
          valueFrom:
            secretKeyRef:
              name: otp-hsl-java-opts-prod
              key: otp-hsl-java-opts-prod
        resources:
          requests:
            memory: "9216Mi"
            cpu: "6000m"
          limits:
            memory: "9216Mi"
            cpu: "7600m"
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: opentripplanner-hsl-pdb
spec:
  minAvailable: 75%
  selector:
    matchLabels:
      app: opentripplanner-hsl
