apiVersion: v1
kind: Service
metadata:
  name: opentripplanner-waltti-alt-v2
  labels:
    app: opentripplanner-waltti-alt-v2
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: opentripplanner-waltti-alt-v2-service-port
