---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-data-builder-hsl
spec:
  schedule: "25 6 * * *" # schedule in Finland time
  timeZone: "Europe/Helsinki"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-data-builder-hsl
        spec:
          priorityClassName: high-priority
          activeDeadlineSeconds: 3600 # one build can take max 1 hour
          restartPolicy: OnFailure
          nodeSelector:
            agentpool: builderpool
          tolerations:
          - key: "builder"
            operator: "Equal"
            value: "yes"
            effect: "NoSchedule"
          containers:
          - name: otp-data-builder-hsl
            image: hsldevcom/otp-data-builder:v2-prod
            volumeMounts:
            - mountPath: /opt/otp-data-builder/storage
              name: datastorage
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: BUILDER_TYPE
              value: "HSL prod"
            - name: DOCKER_AUTH
              valueFrom:
                secretKeyRef:
                  name: docker-auth
                  key: docker-auth
            - name: DOCKER_TAG
              value: "v2-prod"
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: docker-user
                  key: docker-user
            - name: SLACK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-access-token
                  key: slack-access-token
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slack-ci-channel-id
                  key: slack-ci-channel-id
            - name: OTP_TAG
              value: "v1-prod"
            - name: ROUTERS
              value: "hsl"
            - name: SEED_TAG
              value: "v2-prod"
            - name: TOOLS_TAG
              value: "v2-prod"
            - name: VERSION_CHECK
              value: "HSL"
            - name: NOSEED # TODO remove this when seed is ready
              value: "true"
            resources:
              requests:
                memory: 11Gi
                cpu: 7000m
              limits:
                memory: 11Gi
                cpu: 8000m
          imagePullSecrets:
            - name: hsldevcomkey
          volumes:
            - name: "datastorage"
              persistentVolumeClaim:
                claimName: otp-data-builder-hsl-v2-pvc
---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-data-builder-hsl-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-data-builder-hsl
