apiVersion: v1
kind: Service
metadata:
  name: pelias-data-container
spec:
  ports:
  - port: 9200
    targetPort: 9200
    name: pelias-data-container-service-port-1
    protocol: TCP
  - port: 9300
    targetPort: 9300
    name: pelias-data-container-service-port-2
    protocol: TCP
  selector:
    app: pelias-data-container
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelias-data-container
  labels:
    app: pelias-data-container
    update: auto
    restartAt: "05.00"
    restartLimitInterval: "720"
spec:
  replicas: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pelias-data-container
  template:
    metadata:
      labels:
        app: pelias-data-container
        lastRestartDate: dummy-value
        restartAfterDeployments: "pelias-api"
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pelias-api
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        agentpool: powerpool
      tolerations:
      - key: "powerPod"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      containers:
      - name: pelias-data-container
        image: hsldevcom/pelias-data-container:prod
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 9200
          name: vip0
        - containerPort: 9300
          name: vip1
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 9200
            path: /_search?q=name.fi:helsinki
        livenessProbe:
          initialDelaySeconds: 600
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
          httpGet:
            port: 9200
            path: /_search?q=name.fi:helsinki
        env:
        - name: ES_HEAP_SIZE
          value: 3g
        resources:
          requests:
            memory: 4Gi
            cpu: 2000m
          limits:
            memory: 4Gi
            cpu: 3000m
      imagePullSecrets:
        - name: hsldevcomkey

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pelias-data-container-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: pelias-data-container

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pelias-data-container-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pelias-data-container
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
      - type: Percent
        value: 100
        periodSeconds: 90
    scaleDown:
      stabilizationWindowSeconds: 300 # 5 min
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
