apiVersion: v1
kind: Service
metadata:
  name: pelias-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: pelias-api-service-port
    protocol: TCP
  selector:
    app: pelias-api
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelias-api
  labels:
    app: pelias-api
    update: auto
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: pelias-api
  template:
    metadata:
      labels:
        app: pelias-api
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pelias-api
                  - opentripplanner-varely-v2
                  - opentripplanner-waltti-alt-v2
                  - opentripplanner-kela-v2
              topologyKey: kubernetes.io/hostname
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pelias-data-container
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        agentpool: powerpool
      tolerations:
      - key: "powerPod"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      containers:
      - name: pelias-api
        image: hsldevcom/pelias-api:prod
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: /v1/search?text=helsinki
        livenessProbe:
          initialDelaySeconds: 150
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: /v1/search?text=helsinki
        resources:
          requests:
            memory: 3Gi
            cpu: "1000m"
          limits:
            memory: 3Gi
            cpu: "1000m"
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pelias-api-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: pelias-api
