apiVersion: v1
kind: Service
metadata:
  name: raildigitraffic2gtfsrt
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: raildigitraffic2gtfsrt-service-port
    protocol: TCP
  selector:
    app: raildigitraffic2gtfsrt
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: raildigitraffic2gtfsrt
  labels:
    app: raildigitraffic2gtfsrt
    update: auto
    restartAfterDeployments: "opentripplanner-data-con-finland_opentripplanner-data-con-hsl"
    restartDelay: "5"  
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: raildigitraffic2gtfsrt
  template:
    metadata:
      labels:
        app: raildigitraffic2gtfsrt
        lastRestartDate: dummy-value
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - raildigitraffic2gtfsrt
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        pool: defaultpool
      containers:
      - name: raildigitraffic2gtfsrt
        image: hsldevcom/raildigitraffic2gtfsrt:latest-2020-10-13T08.38.10-6d17739
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 2
          httpGet:
            port: 8080
            path: "/hsl"
        livenessProbe:
          initialDelaySeconds: 1400
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
          httpGet:
            port: 8080
            path: "/hsl"
        env:
        - name: API_BASE_URL
          value: "https://api.digitransit.fi/routing-data/v2/"
        - name: ROUTER_ZIP_URL
          value: "https://api.digitransit.fi/routing-data/v2/finland/router-finland.zip"
        resources:
          requests:
            memory: "1536Mi"
            cpu: "200m"
          limits:
            memory: "1536Mi"
            cpu: "1000m"
      imagePullSecrets:
        - name: hsldevcomkey

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: raildigitraffic2gtfsrt-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: raildigitraffic2gtfsrt
