---
service_name: "{{project}}-{{az_environment}}-fav-service"
resource_group_name: "{{service_name}}-rg"

# Redis
redis_name: "{{project}}-{{az_environment}}-redis"
redis_sku: Standard
redis_vm_size: c0

# Function app
storage_account_name: "{{az_environment}}favservice"
storage_sku: Standard_LRS
runtime_stack: node
runtime_version: 10
os_type: Windows
